### ISSUE TITLE
Search engine on list of profiles pages

### ISSUE THREAD

**Issue by MaartenLMEM** [dis-moi/extension#1005]
Main story : If I discovered DisMoi through a profile I want find it back after I installed DisMoi

**Remarque 1 :**  Si l'utilisateur recherche de façon libre, au moment où il valide, la page de résultat chargée décoche automatiquement tous les filtres 
CàD pas de combinaison entre filtre et recherche libre

**Remarque 2 :**  Pas de recherche libre sur mobile pour l'instant

**Comment by newick** [comment]
you mean, we need to find a good solution for new Users after they installed the extension?

The question could be: what the simplest way to help them to find where they come from?

Are we sure we can't find a way to set a param to redirect after installatio?

**Comment by MaartenLMEM** [comment]
It s quite complex to design first and there are technical questions yes.
Here I just mentionned one story. There are many others : 
- I installed Dismoi and I want to look if a friend is there
- I want to find vegan accounts
- I want to find a contributor I follow to see some examples I want to show to a friend
- etc.
Search engine is an obvious solution here. 

Now, I need some design insight to decide where to put it on desktop and mobile UI.

**Comment by MaartenLMEM** [comment]
See screen 38 : https://xd.adobe.com/view/05beeac6-8744-48cf-6e31-647bef2d034a-738f/screen/d0e6df1e-b501-4f34-8615-c97c41754a32/

**Comment by newick** [comment]
@MaartenLMEM Summary of our call with Grégoire:
- search is triggered by the button, no live search
- even if there's a filter chosen, the search will be on the whole list of contributors. To have a search in the chosen filter cost more
- Grégoire suggest a "Clean filters" to reset filters and search and go back to initial state
- under the search form, over the contributors list, one will display something like "Résultat(s) de la recherche 'word' :"
- question about the limit of the search. If the User search "info" does it search "infos" and "info" or only "info" ? (@gregoirelacoste it could mean that it searches "informations" as well, right?)
- one nice visual feature is to highlight the search word in the page. Warning about the performances to do so.

**Comment by MaartenLMEM** [comment]
>     * Grégoire suggest a "Clean filters" to reset filters and search and go back to initial state
To make it simple I imagine just change selected filter to "tous". It s not ideal but I do not see to much cost in UX here.

>     * question about the limit of the search. If the User search "info" does it search "infos" and "info" or only "info" ? (@gregoirelacoste it could mean that it searches "informations" as well, right?)

Results contains typed words.
So yes if user's request is`"info" i`t will show contributors titles and descriptions containing `"informations" `

>     * one nice visual feature is to highlight the search word in the page. Warning about the performances to do so.
Agree.

**Comment by MaartenLMEM** [comment]
Filters widget is not responsive on my mobile phone : Samsung Galaxy S8 - Version Android 9
Screenschot here : https://drive.google.com/file/d/1LWuAy9O7F8TVyyIu3dHVimH89_c3GR8A/view?usp=sharing

**Comment by gregoirelacoste** [comment]
@newick responsive is for you ?

**Comment by gregoirelacoste** [comment]
@J-oh-n responsive looks like this : 
![image](https://user-images.githubusercontent.com/60737012/125451333-5448288d-2963-499e-9375-2006a18a0115.png)

**Comment by J-oh-n** [comment]
tu peux remplacer "entrez votre recherche" par "rechercher un profil contributeur" ?
