### ISSUE TITLE
Load video on Onboarding Prod

### ISSUE THREAD

**Issue by gregoirelacoste** [dis-moi/extension#1006]
Load video mp4 inside js bundle
use Webpack chunk and React Lazy

**Comment by JalilArfaoui** [comment]
https://fr.reactjs.org/docs/code-splitting.html

**Comment by JalilArfaoui** [comment]
You can tell Webpack to embed mp4 files in the chunk here : https://github.com/dis-moi/extension/blob/master/webpack/config.rules.js

**Comment by gregoirelacoste** [comment]
> You can tell Webpack to embed mp4 files in the chunk here : https://github.com/dis-moi/extension/blob/master/webpack/config.rules.js

are you sure, isn't here : https://github.com/dis-moi/extension/blob/master/webpack.profiles.config.js ?
