### ISSUE TITLE
Order contributors with a relevant social proof

### ISSUE THREAD

**Issue by MaartenLMEM** [dis-moi/extension#1009]
Quel critère pour classer les contributeurs de façon transparente ?
Idées :

- `Contributions vues 1448 fois` : non ça s’insère pas bien dans les éléments
-  `59 followers` : pas assez (?)
- `1652 affichages` : ça fait pub
-  `1589 consultations` ? Données en cours de collecte : https://github.com/dis-moi/backend/issues/390

Previous work on it -2020) ; https://docs.google.com/spreadsheets/d/1GY4x70e-Kd4ehpUv_5JAZiyFG8-0R8ki2UKgG8XTLNE/edit#gid=1815461807

**Comment by MaartenLMEM** [comment]
##Rankings 

**Pertinence / Relevancy **
1. Equipe Dismoi - 53 - 52,56 %
2. Podcast Generation Do It Yourself -  20 - 43,75 %
3. voxit - 50 - 43,05 %
4. Kalivi - 11 - 40,54 %
5. Info ou Intox ? - 36 - 40,52 %
6. CaptainFact.io - 431 - 34,3 %
7. Selon Micode - 48 - 32,17 %
8. newick - 49 - 31,27 %
9. Biet Thomas - 63 - 30,36 %
10.  Le Même en Open Source -  180  - 29,17 %
11.  Selon Les Inrocks - 28 - 26,67 %
12. Selon Anticor - 33 - 26,48 %
13. Jalil Arfaoui- 84 - 26,16 %
14. Frédéric - 57 - 25,79 %
15. AdrZcn - 39 - 24,57 %
16. Nothing but my Opinion 81
...
19. Loom - Moins mais mieux _ 107 - 22,63 %
21. Camille 110 _ 22,24 %
25. Amazon Antidote _ 833 _ 18,38 %
34. Maarten _ 322 _ 12,1 %
36. Le Même en Local _ 917 _ 11,45 %
37. Le Même en Moins Cher _ 356 _ 11,18 %
38. John _ 117 _ 10,63 %
39. Maz _118 _ 10,46 %
40. Arnaque Blocker _ 1 207 _ 10,09 %
41. Le Même en Mieux _ 2 544 _ 9,69 %

**Comment by MaartenLMEM** [comment]
**Couverture d'expérience - Web UX coverage **
1. Le Même en Mieux - 1 438 - 6 758
2. Le Même en Local - 517 - 2 068
3. Amazon Antidote - 474 - 1 830
4. Arnaque Blocker - 631 - 1 765
5. Selon Les Numériques - 194 - 1 497
6. On N'est Plus Des Pigeons ! - 137 - 1 442
7. Selon Que Choisir -  519 - 1 384
8. Selon Le Monde - 244 1 011
9. Le Même en Moins Cher - 201 - 868
10. Karim - 30 - 584
...
12. Colibri écolo - 216 - 545
13. Maz -  69 - 498
14. Alternatives gratuites - 129 - 392
15. Maarten - 165 - 343
16. CaptainFact.io - 214 - 337
17. Ethi'Kdo - 156 - 314
18. Equipe Dismoi
...

**Comment by MaartenLMEM** [comment]
**Nombre de bulles consultées - avril**

1. Le Même en Mieux - 631
2.  Le Même en Local - 205
3.  Arnaque Blocker -  200
4.  Amazon Antidote -  174
5. Selon Que Choisir - 114
6. Selon Le Monde - 102
7. CaptainFact.io - 86
8. Selon Les Numériques - 74
9.  Le Même en Moins Cher - 74

**Comment by MaartenLMEM** [comment]
ok vu avec Marco et John, nous allons mettre le nombre de followers et trier les contributeur par nombre de followers

**Comment by MaartenLMEM** [comment]
Vu avec Marco :
- Au dessus de 999 passer à Nk abonnés
- Si 1 écrire abonné au singulier (si pénible, écrire abonné(s)
Exemples : 
Joe - 1 abonné
Maarten - 345 abonnés
Marco - 4 abonnés
Alertoo - 2,0K abonnés
Le Même en Mieux - 5,5K abonnés 
Monsieur Dans le Mille - 1,0 K abonnés

**Comment by gregoirelacoste** [comment]
@MaartenLMEM @newick est-ce qu'il serait pertinent d'avoir un filtre dans le dropdown: `par abonnées` ?

**Comment by MaartenLMEM** [comment]
En fait il s'agirait de mettre un tri dans les filtres ? Après les 4 filtres par exemple séparé par un tiret ? 
Si on met une telle option de tri `par nb abonnés` pré cochée alors il faudra une alternative de tri, par exemple le `nb de contributions`  
Le souci c'est que la valeur de sélection apportée est faible par les autres tri, en plus de devoir afficher ces valeurs. 

Donc au final je n'y vois pas d'intérêt. Mais je ne sûr de bien comprendre les raisons de ton idée.

**Comment by MaartenLMEM** [comment]
@gregoirelacoste, have a look on proding : https://proding-profiles.dismoi.io/eclaireurs Contributors are no more ordered as it was : by number of contributions. 
Note that we ll soon go to number of followers, as you worked on it : https://github.com/dis-moi/extension/issues/1009 Maybe it will solve this issue in same time ?

**Comment by gregoirelacoste** [comment]
> @gregoirelacoste, have a look on proding : https://proding-profiles.dismoi.io/eclaireurs Contributors are no more ordered as it was : by number of contributions. 
> Note that we ll soon go to number of followers, as you worked on it : https://github.com/dis-moi/extension/issues/1009 Maybe it will solve this issue in same time ?

Its ordered by language in staging ans proding. This issue will also change the order

**Comment by MaartenLMEM** [comment]
@gregoirelacoste its s ok but in the wrong order. It should be decreasing, thus start by most popular profiles

**Comment by MaartenLMEM** [comment]
Hum I cannot see the fix.  Maybe it s not deployed on profiles page @gregoirelacoste ?  
![image](https://user-images.githubusercontent.com/7824485/126068630-51a7510a-bca8-4682-b2f4-d1130e8424a8.png)

**Comment by MaartenLMEM** [comment]
It s ok ! Probably my browser cache was the issue.
