### ISSUE TITLE
Contributors are not preselected after installing

### ISSUE THREAD

**Issue by MaartenLMEM** [dis-moi/extension#1012]
During user testing, Dorothee on Computer Apple Firefox installed Dismoi from the website / firefox store.
After dismoi add-on installed, she read message, "we preselected some contributors for you", but when she arrived on list of contributors; no one was preselected.

**Comment by MaartenLMEM** [comment]
![image](https://user-images.githubusercontent.com/7824485/119982870-ad2d0680-bfbf-11eb-9235-66a52e177504.png)

**Comment by JalilArfaoui** [comment]
Tell me if you need help @gregoirelacoste

**Comment by lutangar** [comment]
To clear extension storage:

1. Open background script (`background.html`)
2. Enter `chrome.storage.sync.clear()` in the console

**Comment by MaartenLMEM** [comment]
Contributors are still not preselected after installing DisMoi.
Tested on Version 3.77.1 - Chrome Proding unpacked

**Comment by MaartenLMEM** [comment]
Will be tested in production chrome
