### ISSUE TITLE
New blocks with What s DisMoi and vidéo have disappeared on list of profils pages : staging and proding

### ISSUE THREAD

**Issue by MaartenLMEM** [dis-moi/extension#1027]
Je souhaite voir les dernières petites modifs sur les nouveaux blocks des pages profils pour les visiteurs non connectés (sans extension) et là : https://staging-profiles.dismoi.io/eclaireurs/13/Maarten
Aucun block n'apparait au dessus des profils suggérés, même en navigation privée. ni sur chrome ni sur firefox.

**Comment by lutangar** [comment]
Fixed  https://staging-profiles.dismoi.io/eclaireurs/13/Maarten

**Comment by MaartenLMEM** [comment]
@lutangar de mon côté ça n'a pas changé, les blocks sont toujours invisibles en staging et proding 
Visite de https://staging-profiles.dismoi.io/eclaireurs/13/Maarten en navigation privée sans extension 
3 heures sont passée depuis ta modif j'ai du mal à croire que c'est du cache mais peut-être avec WP ?
![image](https://user-images.githubusercontent.com/7824485/120390777-69732d80-c32e-11eb-857a-3733bbd70f8e.png)

**Comment by MaartenLMEM** [comment]
ce matin sur mon même ordinateur portable, toujours pas les nouveaux blocs visibles en navigation privée sans extension

**Comment by lutangar** [comment]
I don't know private navigation works but this is definitely a cache issue.
In production we have a mechanism to force client cache refresh, but not in staging, in staging you'll have to Ctrl+F5.

**Comment by MaartenLMEM** [comment]
Sur Firefox, j'avais bien fait le CTrl F5. J'ai aussi vidé tout mon cache. CA n'apparait pas. 
Grégoire a testé , il a le même problème.

En revanche, sur Chrome ça marche bien pour nous deux.

**Comment by lutangar** [comment]
Oh you're absolutely right, I see what's going on, ping me @gregoirelacoste  or I'll provide a fix.

**Comment by gregoirelacoste** [comment]
@lutangar ping pr here ;) : https://github.com/dis-moi/extension/pull/1031
