### ISSUE TITLE
Replace default profile banner : instead of DisMoi branded one, use the blue one

### ISSUE THREAD

**Issue by MaartenLMEM** [dis-moi/extension#1045]
This will impact web and mobile version in a soon future.

Blue banner is here  : https://drive.google.com/file/d/1pu2PyScXbrvETBfYBlWAQOKVjWNBeBqS/view?usp=sharing

Examples of profile that will be impacted : 
- https://proding-profiles.dismoi.io/eclaireurs/95/PaKo

**Comment by newick** [comment]
@MaartenLMEM there's an opacity on the default one. 

with opacity
![image](https://user-images.githubusercontent.com/657454/121493318-017cb100-c9d8-11eb-8c6b-85918ef516fc.png)

without opacity
![image](https://user-images.githubusercontent.com/657454/121493487-2bce6e80-c9d8-11eb-8837-445d62f07a96.png)

My 2cts is without it it follows the charted colors
