### ISSUE TITLE
PH : notices name, contributor and relay (instead of only noticeID)

### ISSUE THREAD

**Issue by zhinu** [dis-moi/extension#1056]
Add to events that include notices the following properties:
- notice name
- contributorID 
- Contributor name
- Relayor (contributorID)
- Relayor name

**Comment by lutangar** [comment]
> notice name

@zhinu to which notice property were you referring to?

https://github.com/dis-moi/extension/blob/9f443416a4bb37f575ffe1d2900e1e1ba517e052/src/libs/domain/notice.ts#L6-L29

**Comment by zhinu** [comment]
> > notice name
> 
> @zhinu to which notice property were you referring to?
> 
> https://github.com/dis-moi/extension/blob/9f443416a4bb37f575ffe1d2900e1e1ba517e052/src/libs/domain/notice.ts#L6-L29

i was referring to the text embedded in a notice
