### ISSUE TITLE
Proding : profiles page  linked by the add-on should be https://proding-profiles.dismoi.io/eclaireurs

### ISSUE THREAD

**Issue by MaartenLMEM** [dis-moi/extension#1089]
Problem : 
Since a recent version, as user, if I install proding add-on on my browser, or if I click on "Gérer mes contributeurs", it opens https://www.dismoi.io/eclaireurs/

It should open  https://proding-profiles.dismoi.io/eclaireurs

**Comment by lutangar** [comment]
Should be fixed in last release:
https://github.com/dis-moi/extension/releases/tag/v3.86.3
