### ISSUE TITLE
During Onboarding the cookie bar hides various buttons

### ISSUE THREAD

**Issue by zhinu** [dis-moi/extension#1090]
![image](https://user-images.githubusercontent.com/75084558/124296393-3228b400-db5a-11eb-95fa-91311f5888f0.png)
As you can see the cookie bar hides buttons necessary to finish the process.

Firefox and chrome have the same issue. My resolution is 1280x800.

**Comment by MaartenLMEM** [comment]
@coffeeandpixel let s talk about it asap

**Comment by MaartenLMEM** [comment]
Suite : 
- Demander précisions sur résolution et screenshot à Karène (Maarten)
- En attendant, ajouter media query qui réduit hauteur de la fenêtre (Grégoire)
- Voir si on peut pas enlever barre de cookie avec un petit truc pas très propre ^^ (Grégoire)

**Comment by gregoirelacoste** [comment]
J'ai ajouté un script pour cacher la bar de cookie sur la page `?pk_campaign=installed` (un display none appliqué au container si l'url est reconnu)
Il n'était pas possible d'ajouter ce script depuis les options du plugins ces derniers ne sont déclenché qu'après la validation du cookie. Je l'ai donc mis dans les options de script divi : `https://www.dismoi.io/wp-admin/admin.php?page=et_divi_options`

**Comment by coffeeandpixel** [comment]
Hello @gregoirelacoste voici un petit mockup. J'ai réduit la taille du texte et les espaces aussi.
https://xd.adobe.com/view/fd6d23e3-4d30-4d70-b34b-50e24e4f33e5-a83e/

**Comment by gregoirelacoste** [comment]
@coffeeandpixel merci pour le mockup, j'ai pas pu respecter au pixel prêt car j'ai pris des valeurs relatives à la hauteur de l'écran.

Est-ce que ça vous va : 

Comparaison entre 1010*650

Avant : 
![image](https://user-images.githubusercontent.com/60737012/126654116-5d17e2a1-bf3c-40de-8deb-4caef7e71b2b.png)

Maintenant : 
![image](https://user-images.githubusercontent.com/60737012/126654007-14d16807-6698-45da-9401-55f4b3c25654.png)

Maintenant : en 1010*535 (si un jour ça arrive, en dessous ça casse) 
![image](https://user-images.githubusercontent.com/60737012/126654488-e0613dc4-594f-4ee5-897a-cfe60e15529a.png)
