### ISSUE TITLE
As a user I can directly contribute from the NoNotice screen

### ISSUE THREAD

**Issue by newick** [dis-moi/extension#1126]
Instead of choosing between contribute and submit a question, NoNoticeScreen would be like:
- a textearea and a submit button
- next screen: user name and user email and a preview button
- same preview screen as in http://storybook.lmem.net/?path=/story/extension-contribute-02-preview--normal
edit button would send back on the first screen (I don't recall doing something else for the actual workflow)
- same submitted screen as in http://storybook.lmem.net/?path=/story/extension-contribute-submitted--03-submitted

**Comment by MaartenLMEM** [comment]
very nice experience ! great job @newick @gregoirelacoste
