### ISSUE TITLE
My subscriptions were not displayed on profiles page during many seconds (proding 3.86.7 Firefox)

### ISSUE THREAD

**Issue by MaartenLMEM** [dis-moi/extension#1132]
Video here : https://drive.google.com/file/d/1F4hWySFajOazSPNDL1cTFEMRhRaiZGUh/view

**Comment by MaartenLMEM** [comment]
@zhinu can you install last proding version 3.86.7 on firefox and tell me if you encounter the same issue (see video) ?

**Comment by zhinu** [comment]
Same issue encountered on this version!

**Comment by MaartenLMEM** [comment]
@lutangar do you think it is liked to recent changes on Cloudflare ?

**Comment by zhinu** [comment]
The issue remains on my end with  proding version 3.86.7

**Comment by MaartenLMEM** [comment]
Still the same issue on my side.  I found it also in previous add-on chrome version : proding 3.77.1 
Whereas on prod Chrome and Firefox on https://www.dismoi.io/eclaireurs/ there is no problem

To summarize : 
- Long delay happens always on https://proding-profiles.dismoi.io/eclaireurs
- No problem on dismoi.io/eclaireurs

**Comment by gregoirelacoste** [comment]
I can't reproduce the bug could we try together later ? @MaartenLMEM

**Comment by gregoirelacoste** [comment]
I just fixed another issue here : https://github.com/dis-moi/extension/pull/1143 @lutangar

**Comment by MaartenLMEM** [comment]
@gregoirelacoste an important condition to reproduce that is not showned in the video : 
1. unsinstall proding 
2. and install last version proding
3. than go list of profiles page
Sorry I should have documented this process from the start, near the video.

**Comment by MaartenLMEM** [comment]
Cannot reproduce since this issue : https://github.com/dis-moi/extension/issues/1206

**Comment by MaartenLMEM** [comment]
issue has disapeared
