### ISSUE TITLE
Make long local profile names readable on the page listing profiles - Le Même en Nord-Pas-de-Calais etc.

### ISSUE THREAD

**Issue by MaartenLMEM** [dis-moi/extension#1144]
See https://proding-profiles.dismoi.io/eclaireurs profiles beginning with `Le même en ...`
Challenge here is that if we resize one part we ll have to rezise others.

**Comment by MaartenLMEM** [comment]
I cannot veirfy this feature since I cannot reach the proding profile page anymore : https://github.com/dis-moi/backend/issues/464

**Comment by JalilArfaoui** [comment]
@MaartenLMEM https://github.com/dis-moi/extension/issues/1167 is now fixed.

**Comment by prk-dismoi** [comment]
I cannot access the page https://proding-profiles.dismoi.io/eclaireurs therefore cannot check this one again.

**Comment by JalilArfaoui** [comment]
Indeed @prk-dismoi 😭 … I’m working on it, I created an official issue : https://github.com/dis-moi/extension/issues/1188
