### ISSUE TITLE
Rebranding web extension LMEL

### ISSUE THREAD

**Issue by MaartenLMEM** [dis-moi/extension#1148]
Logo, UI, texts... 
We can capitalize here on the work that will be done before on app and website branding.

**Comment by antoinewolff** [comment]
@JalilArfaoui : Je viens de pousser la branche : [extension-rebranding](https://github.com/dis-moi/extension/tree/extension-rebranding). J'ai essayé de passer partout mais j'ai une erreur au lancement de l'app sur Chome : 

<img width="1247" alt="Capture d’écran 2021-11-10 à 18 17 05" src="https://user-images.githubusercontent.com/12514460/141161141-cf55f906-d4f7-4143-b63f-f1bd4170929e.png">

De plus il faut que tu gères [cette partie là](https://github.com/dis-moi/extension/tree/extension-rebranding/src/assets) du code : 

<img width="1247" alt="Capture d’écran 2021-11-10 à 18 18 32" src="https://user-images.githubusercontent.com/12514460/141162135-6ff4fcc7-bac2-4222-a726-2b9f80ef9ef0.png">

**Comment by JalilArfaoui** [comment]
You’ve mistaken in images path and `icons` indexing … it’s fixed

**Comment by JalilArfaoui** [comment]
I created the PR and will take care of the points you mentionned

**Comment by JalilArfaoui** [comment]
@antoinewolff I’ve taken care of all the steps you mentioned, the `extension-rebranding` is pushed, up-to-date with master, passing the tests and the PR is ready (#1182)

I let you check that all is OK for you and update and/or merge the PR.

**Comment by antoinewolff** [comment]
@JalilArfaoui : `lmel development chromium` is not starting for me : 

`
ERROR in ./src/app/content/index.ts
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './plugin-bugfixes' is not defined by "exports" in /Users/antoinewolff/localhost/extension/node_modules/babel-preset-react-app/node_modules/@babel/compat-data/package.json
`

`
ERROR in ./src/app/background/index.ts
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './plugin-bugfixes' is not defined by "exports" in /Users/antoinewolff/localhost/extension/node_modules/babel-preset-react-app/node_modules/@babel/compat-data/package.json
`

**Comment by JalilArfaoui** [comment]
Seems like a missing `yarn install`...?
