### ISSUE TITLE
Default subscriptions on LMEL app and extension

### ISSUE THREAD

**Issue by MaartenLMEM** [dis-moi/extension#1149]
Default value for LMEL will be different from DisMoi. 
Yet feature is the same, managed in a file that we can change here throught a Github file.

**Comment by JalilArfaoui** [comment]
@MaartenLMEM Do we have the list ?

**Comment by MaartenLMEM** [comment]
Here is a first list : 
25, 35, 40, 61, 118 (Loom, moins mais mieux), 130, 140, 153, 161, 165, 166, 167, 170, 172, 173, 174, 175, 176, 177, 178, 179, 181, 182, 183 and 60 (Amazon Antidote)

**Comment by JalilArfaoui** [comment]
@MaartenLMEM you gave me the same list as in #1151 … Here we want to know all the contributors that users are subscribed to **by default**

**Comment by JalilArfaoui** [comment]
Thanks, Done.
