### ISSUE TITLE
Get only Local contributors on LMEL extensions (Chrome & Firefox)

### ISSUE THREAD

**Issue by MaartenLMEM** [dis-moi/extension#1151]
**Describe the feature/improvement**
Currently Dismoi browser extension gets 
- all contributors with minimum 1 bubble
- all public bubbles 

LMEL browser extension just needs 
- local contributors 
- bubbles they made
- bubbles they relayed

**Technical implementation notes**
Any ideas you have about how this could be implemented.

**Additional context**
Will follow https://github.com/dis-moi/backend/issues/458

**Comment by JalilArfaoui** [comment]
Still waiting for https://github.com/dis-moi/backend/issues/458 …

**Comment by JalilArfaoui** [comment]
We decided that we will maintain a list of accessible contributors as an environnment variable, so we don’t need https://github.com/dis-moi/backend/issues/458 anymore

**Comment by JalilArfaoui** [comment]
@MaartenLMEM can you provide this list of ids of contributors we consider `local` so that I limit subscriptions to them ?

**Comment by MaartenLMEM** [comment]
@JalilArfaoui Here is the list :
25, 35, 40, 61, 118 (Loom, moins mais mieux), 130, 140, 153, 161, 165, 166, 167, 170, 172, 173, 174, 175, 176, 177, 178, 179, 181, 182, 183 and 60 (Amazon Antidote).

**Comment by MaartenLMEM** [comment]
Update : Just added 43 (Le même d’occasion)

**Comment by JalilArfaoui** [comment]
@MaartenLMEM you gave me the same list as in #1149 … Here we want to know all the contributors that users *can* subscribe to …

**Comment by MaartenLMEM** [comment]
cannot verify it until this other issue is solved : https://github.com/dis-moi/extension/issues/1178
