### ISSUE TITLE
Plug posthog on LMEL extension like we did with dismoi

### ISSUE THREAD

**Issue by MaartenLMEM** [dis-moi/extension#1152]

**Comment by JalilArfaoui** [comment]
@MaartenLMEM the way I did things for LMEL version, every behavior not stated different is the same as in DisMoi version … 

So PostHog is already operational … Is there anything we want to track differently ?

**Comment by MaartenLMEM** [comment]
I don't see any specific tracking need here. Thanks.

**Comment by prk-dismoi** [comment]
@MaartenLMEM @JalilArfaoui how do we test this?

**Comment by MaartenLMEM** [comment]
@prk-dismoi I just sent you an invitation to Posthog. 
About this feature : it's SHOULD HAVE but not mandatory : We don't need to test it before lauching our product. 
So I see it this way : today there are no events, so it is hard to assess for us. 
So let's put this feature on done and cross fingers. 
And if something does not work later, we create a new issue.

**Comment by prk-dismoi** [comment]
ok, moving the ticket.
