### ISSUE TITLE
Diverge i18n resources with DisMoi and LMEL sections

### ISSUE THREAD

**Issue by JalilArfaoui** [dis-moi/extension#1155]

**Comment by J-oh-n** [comment]
> @J-oh-n @newick Do you have an idea which texts are going to be different between DisMoi and LMEL facets in https://github.com/dis-moi/extension/blob/master/src/libs/i18n/resources/fr/extension.json ?
> 
> I’m not sure we’ll have that much differences …

=> we will see it during testing, you can move on

**Comment by prk-dismoi** [comment]
Hey @JalilArfaoui can I move this one to "Ready for prod"?

**Comment by JalilArfaoui** [comment]
Yes

**Comment by JalilArfaoui** [comment]
Yes
