### ISSUE TITLE
Proding profiles page of LMEL is the same as Dismoi

### ISSUE THREAD

**Issue by MaartenLMEM** [dis-moi/extension#1178]
Problem : 
https://proding-profiles.dismoi.io/eclaireurs : contributors page adress is the same for LMEL as for Dismoi. Therefore, the list of contributors is the same, while it should be a restricted list of local ones.

To reproduce : 
1. Install LMEM proding (or staging)
2. onboarding opens
3. choose contributors and validate
4. it open list of contributor page :  https://proding-profiles.dismoi.io/eclaireurs?pk_campaign=installed-contributors-list

**Comment by prk-dismoi** [comment]
An additional issue which might warrant its own ticket.
From abroad, my browser opens: https://lememe.fr/en/guides/?pk_campaign=installed upon installation of the latest Firefox proding extension (3.93.5)

**Comment by JalilArfaoui** [comment]
Yes, please @prk-dismoi so that we can keep track of what needs to be done

**Comment by prk-dismoi** [comment]
> Yes, please @prk-dismoi so that we can keep track of what needs to be done

Thanks. Created an investigation ticket here: https://github.com/dis-moi/extension/issues/1189
Once its clear what we do with EN I'll review the flows and write up precise tasks accordingly (if needed).
