### ISSUE TITLE
When the installation pop-up is open inviting me to install LMEL, if I click I am redirected to Dismoi addon store page instead of LMEL's.

### ISSUE THREAD

**Issue by MaartenLMEM** [dis-moi/extension#1232]
Instead of Dismoi addon store page, I should be redirrected to LMEL one's.

Chromestore LMEL address : https://chrome.google.com/webstore/detail/le-m%C3%AAme-en-local/heoimefmbpfjhpiepkomlkijgmlappko 
Firefox LMEL address : https://addons.mozilla.org/fr/firefox/addon/lememe/

![image](https://user-images.githubusercontent.com/7824485/151192963-3a8e390e-5a05-40fd-9b8b-4e5e47cd51dd.png)

**Comment by JalilArfaoui** [comment]
I'll take a look at this

**Comment by JalilArfaoui** [comment]
Verified in production
