### ISSUE TITLE
Page abonnements Dismoi : url opened does not work : page not found

### ISSUE THREAD

**Issue by MaartenLMEM** [dis-moi/extension#1238]
Since we updated Dismoi extension in production, the profiles page (and thus the onboarding) is broken.

**To reproduce onboarding bug :** 
1. Install Dismoi prod
2. Onboarding opens a new tab with https://www.dismoi.io/profils?pk_campaign=installed and this page is empty : "La page demandée est introuvable. Essayez d'affiner votre recherche ou utilisez le panneau de navigation ci-dessus pour localiser l'article."
Previously it opened : https://www.dismoi.io/eclaireurs?pk_campaign=installed

**To reprodruce profiles page bug**
1. Install Dismoi prod
2. Right clic on the D and go to "Comptes suivis"
3. Its opens https://www.dismoi.io/profilswith  "page not found".

This is related to recent change on list of profiles page url for LMEL.

Yet, LMEL profiles pages and onboarding are working well.

**Comment by JalilArfaoui** [comment]
@MaartenLMEM I published profiles V1 to production (it was still with old URL …). Seems good to me now …
