### ISSUE TITLE
Please disable console.log on production

### ISSUE THREAD

**Issue by thomasbnt** [dis-moi/extension#1256]
I'm a developer, and most of my times, I've got the DevTools opened. But with the [Dismoi](https://chrome.google.com/webstore/detail/dismoi/fpjlnlnbacohacebkadbbjebbipcknbg) extension, I've got issues.

Please disable logs and warning issues.

![image](https://user-images.githubusercontent.com/14293805/172678479-bb3742eb-2d6c-4f60-9f62-3ec8729115b4.png)

**Comment by JalilArfaoui** [comment]
Hello @thomasbnt thanks for reporting

Seems like we have to reopen https://github.com/dis-moi/extension/issues/878
