### ISSUE TITLE
Move away sensible informations

### ISSUE THREAD

**Issue by bmenant** [dis-moi/extension#153]
In order to open sources up, sensible configuration values (i.e. hosts origins) should not be staged with git.

**Comment by lutangar** [comment]
@JalilArfaoui I'd like to say it's not relevant since we open sourced the project. 


>  (i.e. hosts origins) 

...were considered *sensible* configurations values. We're indeed not committing secrets but still we are committing env files variations.

**Comment by JalilArfaoui** [comment]
We can close this I think @lutangar !
