### ISSUE TITLE
Messaging Error: “Could not establish connection. Receiving end does not exist.”

### ISSUE THREAD

**Issue by bmenant** [dis-moi/extension#241]
AFAIK, this bug does not block the extension and has no visible effect on the behavior of the extension.

![connection_error_firefox](https://user-images.githubusercontent.com/756887/54022249-56467700-4192-11e9-8312-2d4c03163e3d.png)

Apparently, `Error: Could not establish connection. Receiving end does not exist.` is thrown when one attempts to communicate (e.g. `tabs.sendMessage()` or `tabs.connect()`) with a tab where there is no listener for messages in any contentScript (and when there is no contentScript in the tab).

It occurs rarely on development build, but when it does, Firefox reports error from [`sendToTab.js`](https://github.com/insitu-project/recommendations-webextension/blob/v2.x/src/app/background/services/sendToTab.js).

The error has been reported on both Chrome & Firefox browsers.

**Comment by christpet** [comment]
@JalilArfaoui is this still happening? If no effect on extension... I say we take it off "high priority"

**Comment by lutangar** [comment]
Agreed. I think it's still happening, but don't think it's impacting the users.

**Comment by christpet** [comment]
Ok closing since no impact... we can reopen if we think it is having an impact!
