### ISSUE TITLE
Dismissed error when backend fails to handle Ratings post

### ISSUE THREAD

**Issue by bmenant** [dis-moi/extension#256]
Related QA: `RA_003` `RA_005`

If the backend server fails for whatever reason (e.g. overloading) to handle a rating post request, the corresponding redux action is not reverted and the error is not shown to user. 

An error screen or info is expected to be shown to user in such cases. The redux action should also be reverted (or by passed).

**Comment by christpet** [comment]
No action on this for 2 years = closing until further notice!
