### ISSUE TITLE
Network Errors Handling & Recovering

### ISSUE THREAD

**Issue by bmenant** [dis-moi/extension#257]
In some circumstances (system suspend/wakeup), some errors such as `net::ERR_INTERNET_DISCONNECTED` and `net::ERR_NETWORK_IO_SUSPENDED` are thrown when the extension attempts to fetch matching contexts and/or notice.

As a result, the extension does not open and users think it doesn’t work. In some cases, it seems the browser kind of suspends the whole extension for its own safety (but this has yet to be confirmed). 

- At first, AFAIK error handling is a topic we already mention but didn’t really addressed yet. It goes beyond those network errors.

- Then, it turns out the extension initiates some HTTP requests that never end. As a matter of fact, if the system goes offline (i.e. suspend/hibernate or connection loss) while a request is on going, as the browser resumes, the request remains and waits for an answer that will never come (since the server has closed the connection on its side long ago). This may quickly lead to `net::ERR_NETWORK_IO_SUSPENDED`.

  While the [XHR API](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/timeout) had a `timeout` option to address those sort of issues. On the other hand, the [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API#Aborting_a_fetch) doesn’t provide any `timeout` option, but has been given an abortable trait that allows similar timeout handling (i.e. to abort the request if its hanging on more than 30 seconds).

----

https://trello.com/c/z0eCzeDE/73-les-recos-napparaissent-plus-sur-2-navigateurs-pour-toujours

**Comment by lutangar** [comment]
@JalilArfaoui we could rework this issue description to include the missing error messages and the need of placeholders for these messages.

**Comment by christpet** [comment]
Looks like this might be related to https://github.com/dis-moi/extension/issues/861 @lutangar @JalilArfaoui ?

Otherwise it looks like there's nothing else to do under this issue & i'll close it.
