### ISSUE TITLE
Consider using the WebExtension declarativeContent API

### ISSUE THREAD

**Issue by bmenant** [dis-moi/extension#275]
https://developer.chrome.com/extensions/declarativeContent

> Use the chrome.declarativeContent API to take actions depending on the content of a page, without requiring permission to read the page's content. 

This one sounds pretty good.

**Comment by lutangar** [comment]
I'm copying this message  from the slack :

> 08/01/2020
> C'est comme si l'API chrome declarativeContent avait été faites pour Bulles:
https://developer.chrome.com/extensions/declarativeContent#rules
alors que nous faisons des contorsions de fous pour arriver au même résultat avec pleins défauts en plus...

> Le frein à l'heure actuelle c'est que l'API n'existe pas encore pour firefox. Une autre API de Firefox permet de faire des choses similaire (cela voudrait dire 2 développement différents) :
> https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/contentScripts/register

> La bonne nouvelle c'est que le boulot est en cours chez Mozilla :
> https://bugzilla.mozilla.org/show_bug.cgi?id=1435864

> Et selon ce commentaire la fonctionnalité serait prévu pour Firefox 68:
> 10 months ago 
> Soft freeze is coming up, and this feature cannot be completed before that. For QA, the target will be 68 instead of 67. This will be the last time that the target is moved.

**Comment by lutangar** [comment]
From the Firefox team :
> The development of declarativeContent is currently on hold because the risk of the implementation does not balance against the potential benefits of it. For more details, see https://docs.google.com/document/d/1KjC2uAV0n5BszbyQjclzp2cLiOhWuKrTmqvqyz5ggKU/preview

>There are several alternatives to the declarativeContent API, such as the tabs and webNavigation APIs, and using them results in code that is still compatible with Chrome.

**Comment by christpet** [comment]
Ok, so this is prevented by stalled development within the Firefox team? I'll close it and if you have any objections, please re-open 👍
