### ISSUE TITLE
[extension] Open link in new tab

### ISSUE THREAD

**Issue by newick** [dis-moi/extension#755]
Context: on https://www.oui.sncf/, the extension triggers with le même en mieux's contribution about other websites to find tickets. I tried to click with the scroll wheel. It opened the tab with `https://www.oui.sncf/commande/www.trocdestrains.com?utm_medium=Dismoi_extension_navigateur`

It would be nice if it opened `www.trocdestrains.com?utm_medium=Dismoi_extension_navigateur` when the user uses his mouse wheel or control clicks.

**Comment by gregoirelacoste** [comment]
Hi @newick !
I tried on chrome and firefox but i failed to reproduce the bug. Can you tell me more ?

**Comment by newick** [comment]
Damnit contribution team 😬 !

it seems like it's fixed! Who did that? Reveal yourself! 🚀 

Good news, let's close it!
