### ISSUE TITLE
Youtube Vidéo embedded in notice

### ISSUE THREAD

**Issue by MaartenLMEM** [dis-moi/extension#759]
As a web user, when I read notice in detail view in DisMoi, if there is an url about Youtube I can watch it directly embedded in DisMoi window.
For example, notice 165 from Alertoo visible on https://www.hsbc.fr whole website.

**Comment by MaartenLMEM** [comment]
Hi @christpet  I just tested this feature and I found an issue.

Notice tested : Bulle (#1538)
Page : https://www.lemonde.fr/les-decodeurs/article/2020/09/24/5g-le-vrai-le-faux-et-ce-qu-on-ne-sait-pas-encore_6053447_4355770.html

**Prod layout (current)**
![image](https://user-images.githubusercontent.com/7824485/112954006-48c80500-913e-11eb-9cd1-24f278af369b.png)

**Proding layout :** 
![image](https://user-images.githubusercontent.com/7824485/112953614-ec64e580-913d-11eb-8185-fb39c9842ada.png)

**Comment by MaartenLMEM** [comment]
Same problem with the example hsbc : https://www.hsbc.fr/1/2/hsbc-france/particuliers/devenir-client-ouvrir-un-compte-bancaire-en-ligne

**Comment by christpet** [comment]
@MaartenLMEM thank you for testing and reporting this! @newick is this more appropriate for you or Gregoire?

**Comment by newick** [comment]
@christpet I think that @gregoirelacoste created it, he knows it more.
