### ISSUE TITLE
When I uninstalled the extension from Firefox, it opened bulles.fr

### ISSUE THREAD

**Issue by newick** [dis-moi/extension#765]
It was the same for Marco.

**Comment by gregoirelacoste** [comment]
@christpet i handle it !

**Comment by lutangar** [comment]
@gregoirelacoste we're already supposed to use the up to date `UNINSTALL_ORIGIN` env variable.
You probably should investigate about the version of the extension which were used to produce to the bug.

**Comment by gregoirelacoste** [comment]
@lutangar thx for the context, i will investigate

**Comment by christpet** [comment]
@gregoirelacoste maybe this is related? https://github.com/dis-moi/extension/issues/870

**Comment by newick** [comment]
can't reproduced with last version.

**Comment by gregoirelacoste** [comment]
> can't reproduced with last version.

@christpet do we close this issue ?

**Comment by christpet** [comment]
Same here. Let's close it!
