### ISSUE TITLE
[Profile page] Avatar is distorted 

### ISSUE THREAD

**Issue by newick** [dis-moi/extension#766]
It comes from the WP styles.
A solution can be to reset `max-width`. 

But I thought I already corrected it. It was not pushed to prod ? @lutangar @JalilArfaoui

**Comment by MaartenLMEM** [comment]
Hi @christpet, I do not understand why it s in this column prod chrome.
On mobile, I still see a distorted avatar on mobile, for example here : https://www.dismoi.io/eclaireurs/16/Le-Meme-en-Mieux

**Comment by MaartenLMEM** [comment]
@newick je vois que tu avais une nouvelle correction et qu'elle a été merged en version 3.67.2 

Le 14 avril CaptainFact m'a remonté à nouveau le problème sur mobile (donc en prod)
Je viens de jeter un oeil :
- profils-staging en format mobile, l'avatar est toujours rattatiné sur mobile (voir capture plus bas)
- en prod sur Version 3.61.0 sur me destkop si je réduit la fenêtre en taille mobile - idem 
- sur mobile sans aucune extension tous les avatars des pages profils sont ratatinés, par exemple https://www.dismoi.io/eclaireurs/60/Amazon-Antidote

Quelques hypothèses : 
- un rollback quelquepart ? Comme le problème est partout j'ai du mal à croire en cette hypothèse
- la solution n'a pas résolu le problème et cela a échappé à la recette ? Possible mais peu probable.

![image](https://user-images.githubusercontent.com/7824485/116818178-46f0c780-ab6a-11eb-83de-261946faa9e7.png)

**Comment by newick** [comment]
@MaartenLMEM I don't get it.
In the `master` branch I see the code 
```
          & > img {
            max-width: initial;
            width: 70px;
            height: auto;
          }
```

the same part in the code is 
![image](https://user-images.githubusercontent.com/657454/117163044-90881f00-adc3-11eb-8aa0-f68a0e418985.png)

So the height doesn't in the prod code.

@gregoirelacoste could you look upon that ?

**Comment by gregoirelacoste** [comment]
@newick you right, in staging it's working well. So it will be fixed in the next released.

**Comment by gregoirelacoste** [comment]
>     * profils-staging en format mobile, l'avatar est toujours rattatiné sur mobile (voir capture plus bas)

your screen show prod version

**Comment by MaartenLMEM** [comment]
Ok sorry guys I made a mistake it s ok !
