### ISSUE TITLE
English version - to write specification

### ISSUE THREAD

**Issue by christpet** [dis-moi/extension#771]

**Comment by christpet** [comment]
Notes from Jan 21 meeting:

### UI du produit

- Extension itself  + Profile pages, not much to translate, would be changed in the the extension code
- Extension description
- step 1: put all hardcoded text into a file - 0.5 day
- step 2: translate - 
- step 3: use a library to put the right translation in the right language version - 1 day
- Force a language in the user’s UI (i.e. English-speaking user can change to French language) - ESTIMATE - Julien
- Must have a filter so they see the language they want - ESTIMATE - Julien
- By default show the language they speak, but show other languages when they scroll down or search
- OR add an option where user can select either (english) or (all languages)
- capacité de détection de la langue du navigateur ? oui !
- With an API - 0.5 day

### back-office de contribution ? pas besoin pour le moment (new UI coming, make it in English)

- Add a field to select one language assigned to a contributor
- API gives this information to the extension so they can filter it

### Site web - 5 DAYS

- gros travail sur les textes et copy
- few plugins allow to manage multiple language (https://www.wpbeginner.com/showcase/9-best-translation-plugins-for-wordpress-websites/)

### Contributions? Non.

- But if I am an English-speaking user, the system must show only the contributions/contributors in my language by default
- Should I have the possibility to see contributions in other languages if I want? Yes (see above)
- To create contributors in English - TO ESTIMATE - Maarten
- Contributeur ? langue pas défaut filtrant la liste
- Translation
- Start with translating the core, then will be easier for others 
- Two types of translation:
- For comms, e.g. the website - should not be an exact translation, should be adapted to the new cultural context
- For the UI

**Comment by lutangar** [comment]
@christpet I saw you closed this but I don't see any resolution reason nor a link to the produced *specification*.
Or is it closed because it's not relevant anymore?

**Comment by christpet** [comment]
Closed because #781 contains the basic spec
