### ISSUE TITLE
English version - review the spec and confirm task breakdown

### ISSUE THREAD

**Issue by christpet** [dis-moi/extension#781]
Basic MVP English version includes:

Extension
- Chrome (-> Edge, …)
- Firefox

Backend
- Pages
-- Sources page
-- Contributor Profile pages

Profiles app (now part of extension repo, may later be in website repo)
- Mechanism to recognize language and serve appropriate UI
- Mechanism to show only English contributions

Website
- Landing page
- Nav Menu
- Contribute page
- Help page
- About page

Contributions: Need enough in English

I will break this out into separate issues shortly...

**Comment by lutangar** [comment]
> same comment as in #771 -> why is this closed?

**Comment by christpet** [comment]
I closed this because I had already broken it out into specific tasks on Github. See i18n project https://github.com/orgs/dis-moi/projects/2
