### ISSUE TITLE
Question: What events are we tracking in the extension?

### ISSUE THREAD

**Issue by christpet** [dis-moi/extension#782]
In Matomo, what are these "events" actually tracking?
![image](https://user-images.githubusercontent.com/32476396/108178829-2f767680-7105-11eb-9453-003cbb4000cf.png)

**Comment by MaartenLMEM** [comment]
@christpet It was @lutangar who built up analytics on matomo. I ll know probably better than Jalil.

**Comment by MaartenLMEM** [comment]
I start to answer, tell me if it's what you expected :
- Suscribe = suscribe to an contributor
- Close : extesnion window closed (beacause user clicked on the cross up right the window)
- Click = user clic on extension
etc.
Or do you want more technical informations ?

**Comment by christpet** [comment]
Fantastic thank you @MaartenLMEM that's exactly what we're looking for @zhinu 

That is a LOT of subscribes in one week... is that expected behavior?

**Comment by MaartenLMEM** [comment]
> That is a LOT of subscribes in one week... is that expected behavior?
Yes and no.
Yes : It counts real suscribing events, even when these are automatic
No : Some extensions "loose their mind" about DisMoi : their local storage forget its subscriptions. So we built up a mechanism that suscribe user to  N default contributors if it has zero subscription.

**Comment by christpet** [comment]
Ah wow, that would explain why the number is so big. Really interesting that the extension has amnesia sometimes 😅

Looking at Matomo, it looks like the majority of subscription events are attributable to just 2 users in Ukraine and Australia. Many times per day they log a session where they add 17-22 subscriptions within 2 seconds. There's our automated mechanism.

It's okay for now, we might be able to get better subscription numbers just by filtering out these 2 users. We can look into it for the future.

Right now I'm focused on the usage stats, which are fantastic. Bravo @MaartenLMEM  and @lutangar . I love that we are able to see exactly the user journey people are taking and how they interact, but completely anonymized.

What does it mean when it says "blue" or "grey" next to a content item?

**Comment by MaartenLMEM** [comment]
> Looking at Matomo, it looks like the majority of subscription events are attributable to just 2 users in Ukraine and Australia. Many times per day they log a session where they add 17-22 subscriptions within 2 seconds. There's our automated mechanism.

Look out Chrisitian, those are anonymized users ! They are all differents, and they are in France. Ukraine or Australia is just a way for matomo to anonymize data.

**Comment by christpet** [comment]
Oh wow I didn't realize that even the country is scrambled. Thank you for the heads up!

**Comment by lutangar** [comment]
After a quick discussion with @zhinu we agreed that which should be able to tell apart an automatic subscription from a manual one. This is not currently the case.

@zhinu if you wish to dig this yourself here are a few entrypoints on the tracker code :
**The Tracker interface definition**
https://github.com/dis-moi/extension/blob/master/src/types/Tracker.ts
> You'll find there which properties are available for a `TrackingEvent`
 
**Code triggering the `subscribe` event**
https://github.com/dis-moi/extension/blob/master/src/app/background/sagas/tracking/trackContributor.saga.ts
> You'll see there that we are listening for a `ContributorAction` (a redux action) 

**The action**
This is the action you want to modify to add some `meta` information to it. The meta property would be something like `automatic: boolean` which should default to `false`. (or maybe `manual: boolean` default to true, your call)

First you'll have to modify the definition in `app/actions` and then set this meta to `true` somewhere in :
https://github.com/dis-moi/extension/blob/master/src/app/background/sagas/subscriptions.saga.ts#L72-L81

Once the meta is set, you can go back to `trackContributor.saga.ts` and modify the event sent depending on the value the new `automatic` (or your custom name).

Hope it helps!

**Comment by christpet** [comment]
Since the question was answered, I am closing this issue in favor of the more specific issue https://github.com/dis-moi/extension/issues/842

**Comment by lutangar** [comment]
@christpet if not done yer, we should create a document somewhere from these informations and for future use.
This document could also include info on the backend tracked events and data in general.
Could someway be linked to some of the privacy content we already have.
