### ISSUE TITLE
Remplacer "Source d'informations" par "contributeurs" sur le site et produit

### ISSUE THREAD

**Issue by KaliviArf** [dis-moi/extension#785]
**Sur le site :** 

Remplacer vos sources d'information par "Vos contributeurs" 

![image](https://user-images.githubusercontent.com/78505335/108385367-e3fac000-720b-11eb-8382-449a3b3d5f18.png)

Dans le formulaire : https://form.jotformeu.com/82702852284358
Texte à remplacer : D'autres informateurs pourront également les relayer sur leur propre fil. Remplacer informateurs par contributeurs

![image](https://user-images.githubusercontent.com/78505335/108386875-5ae48880-720d-11eb-9f05-e13f95fde1fc.png)
 

**Dans le produit :** 

Dans le Menu choix de la source = choix du contributeur
![image](https://user-images.githubusercontent.com/78505335/108385651-2b814c00-720c-11eb-9828-98af04e452a7.png)

 ---Et remarque concernant le texte qui s'affiche par défaut Dans le formulaire / L'internaute choisit dans le menu déroulant le choix de son contributeur qu'il souhaite interroger juste au dessus / inutile donc de marquer ensuite dans la fenêtre à mon sens, cette phrase : 
![image](https://user-images.githubusercontent.com/78505335/108388863-5de07880-720f-11eb-8371-6db7851e6148.png)

 Ne laisseriez vous pas uniquement dans cette fenêtre la phrase suivante : 
![image](https://user-images.githubusercontent.com/78505335/108389078-9c763300-720f-11eb-9a46-97473c358d00.png)

**Comment by KaliviArf** [comment]
@christpet @antoinewolff

**Comment by newick** [comment]
C'est là qu'on reparle de la mise en place de l'écriture inclusive ?

**Comment by lutangar** [comment]
> C'est là qu'on reparle de la mise en place de l'écriture inclusive ?

:door: https://github.com/dis-moi/extension/issues/new?assignees=&labels=&template=feature_request.md&title=Gender-Inclusive%20Language
