### ISSUE TITLE
As a user,  I want to be notified when new contributors are available

### ISSUE THREAD

**Issue by JalilArfaoui** [dis-moi/extension#786]
**Describe the feature/improvement**
Every time the extension fetches contributors it never saw, notify the user. The notification could be 
- Badge on the browser icon
- Service message
- Native (OS) notificaton
- Other …

**Target user**
General audience

**Technical implementation notes**
Detecting new contributors is easy : Each time contributors list is fetched, if we already had one in memory and if the new one contains new entries : Bingo

**Comment by newick** [comment]
duplicate with #784 😁

**Comment by JalilArfaoui** [comment]
Argh ! Too late ! 

I’ll update yours with my (better) details 😛

**Comment by JalilArfaoui** [comment]
Closed in favor of #784

**Comment by lutangar** [comment]
Love to see you guys fighting to create an issue :heart_eyes:
