### ISSUE TITLE
Choose i18n library (English Version)

### ISSUE THREAD

**Issue by christpet** [dis-moi/extension#799]

**Comment by gregoirelacoste** [comment]
@christpet @lutangar @JalilArfaoui 
I did a benchmark on 4 known plugins of i18n: React-intl, React-intl-universal, LinguiJS, i18next

**React-intl**: edited by Yahoo, builds upon the intl ECMAScript API, part of formatJS
Easy to use with a component that encapsulate the app. 6 components that meet all of the requirements  (date, time, number, plural, relative, message). Each components also exist as a hook. Matching is done from IDs. 
Disadvantage: only works for react

**React-intl-universal**: (edited by Alibaba) based on the previous lib (React-intl) but not exclusive to react
A get () function allows access to the translation API. It seems to be more readable than the previous one, ex: intl.get ('thetranslate.id', {name: 'myvar'})
Note: loading the translation is done through a promise, then rendering the root application

**LinguiJS**: New plugin with many functions. Interesting to translate an already existing app.
It just need to wrap the text to be translated with the <Trans> component then launch (with the Lingui CLI) the extrat command. This generates a translation file, with the key automatically generated for each line to translate

**i18next**: the leader (1.3M DL weekly), the Swiss knife which does everything we have mentioned above and more. It's not a big deal, but it's a bit more complex to setup. Created in 2011 and constantly evolving, this plugin seems to be the most reliable and mature. It supports all frameworks and is fully configurable, in particular with "interpolation" function which allows integration of dynamic values ​​and the generation of custom formats.

**My recommendation**: despite a greater complexity for setup, i18next seems to be more secure, complete and maintainable in the long term. In the immediate future most of the functions will not be used, but in the medium term they will be very helpfull

**Comment by lutangar** [comment]
> LinguiJS: New plugin with many functions. Interesting to translate an already existing app.
It just need to wrap the text to be translated with the component then launch (with the Lingui CLI) the extrat command. This generates a translation file, with the key automatically generated for each line to translate

I did have a good experience with this one for simple needs.

> My recommendation: despite a greater complexity for setup, i18next seems to be more secure, complete and maintainable in the long term. In the immediate future most of the functions will not be used, but in the medium term they will be very helpfull

I agree! I think `i18next` is the way to go, plus there is a `react` plugin.

**Comment by gregoirelacoste** [comment]
Thank you for your feedback,

Another good point with i18next: we can split our translation between multiple namespaces and call those namespaces depending on the context with loadNamespaces() function or inside translator function t(mynamespace:key).

So I suggest to named the folders by namespaces and then by language, inside the root folder: 

> locales
>>extension
>>> en_GB.json
>>> fr_FR.json

>>webSite
>>> en_GB.json
>>> fr_FR.json

Then for each app (app / content and app / profiles), I will create 2 differents config files: both of them will share the same translation files and namespaces. In this way, if some texts are the same on the two app, the both will be able to access the translation for each other. The only difference will be the default namespace.

Then for each text to translate I will call the hook useTranslation() inside the component and apply the function t("keytoaccessthetext").

What do you think about it ?

**Comment by christpet** [comment]
Sounds great @gregoirelacoste - I will let @lutangar comment on the logic of what you propose but it sounds reasonable to me. 

In your suggestion of the folder structure, by "webSite" does that refer to the Profiles app or the www.dismoi.io wordpress site?

**Comment by gregoirelacoste** [comment]
@christpet thank you for the feedback, yes "website" is "Profiles", so I will name it like that

**Comment by lutangar** [comment]
@gregoirelacoste the extension is actually divided in several apps (more than 2) and I think each app deserve its own namespace.
I don't know about the implementation details but there might be some common translations, don't know if it's a relevant information and don't overthink this part.
Anyway the informations on the extension app structure is already available here:
- https://github.com/dis-moi/extension/blob/master/docs/CONTRIBUTING.md#structure

Also this structure will probably evolve toward what's describe in  #761 

> If it's not already done, don't forget to read existing `docs/`, README, contributing guide and this WIP on the review process https://github.com/dis-moi/docs/pull/1/files

Cheers!

**Comment by gregoirelacoste** [comment]
@lutangar hi, so I will begin by extension and create an dedicated namespace. Then I will continue by Profil with another dedicated namespace. If I see common words, i will create a third namespace : Common. If we have other needs in the future we can always create new namespaces for other apps.

**Comment by lutangar** [comment]
Maybe It wasn't clear enough, but there are __3 apps __ in the `extension` repository:
- `background/`
- `profiles/`
- `content/`

Each having a separate build, so I assume, a separate namespace.
For `common` namespace I let you see if useful or not.
