### ISSUE TITLE
Modifications Menu Extension 

### ISSUE THREAD

**Issue by KaliviArf** [dis-moi/extension#804]
Dans le menu : 
Remplacer Abonnement par "Eclaireurs"
![image](https://user-images.githubusercontent.com/78505335/109136170-1fd7dd00-7758-11eb-9bcb-115bb148c170.png)

Modifier "Vous suivez X sources" par "Vous suivez X éclaireurs"
![image](https://user-images.githubusercontent.com/78505335/109136102-0e8ed080-7758-11eb-9afe-4dc2dc26ede0.png)

Bouton "Gérer mes abonnements" par "Gérer mes éclaireurs"
![image](https://user-images.githubusercontent.com/78505335/109136569-8d840900-7758-11eb-960d-fd10ea2ea664.png)

**Comment by MaartenLMEM** [comment]
@gregoirelacoste sorry for chaging this, but we go back to "Abonnements" instead of "vos éclaireurs" 
Is it possible to simply roll back ?

**Comment by gregoirelacoste** [comment]
@MaartenLMEM to complicate to rollback, you only need to change the word in the translation file
