### ISSUE TITLE
Labels des onglet de la Page https://www.dismoi.io/sources [Quick win]

### ISSUE THREAD

**Issue by KaliviArf** [dis-moi/extension#806]
@christpet @MaartenLMEM @antoinewolff 

Pour cette page : je ne sais pas trop comment différencier le menu "Sources" et le menu "Abonnements" 
Est ce que l'on modifie Sources en "Eclaireurs du web" et on laisse "Abonnements" ou "Eclaireurs que vous suivez" qqch comme cela ?

![image](https://user-images.githubusercontent.com/78505335/109137158-2e72c400-7759-11eb-856b-2c908f606ee9.png)

**Comment by MaartenLMEM** [comment]
Je confirme :  problème identifié fin 2020 en feedback et en test utilisateur. 
Je pensai qu'une issue existait déjà mais je ne l'ai pas trouvé.
**Proposition de modification des labels :** 
Sources => Tous 
Abonnements => Vos éclaireurs

**Comment by christpet** [comment]
Oui je suis d'accord. @MaartenLMEM ton proposal c'est bon ! Except that "Vos eclaireurs" should be on the left à mon avis

**Comment by JalilArfaoui** [comment]
Alternative, si ça peut aider : 

- Tous
- Suivis
