### ISSUE TITLE
Prepare i18n file for translation (French Version) for Extension

### ISSUE THREAD

**Issue by gregoirelacoste** [dis-moi/extension#811]
I suggest to put all text in tranlation file, even french

**Comment by gregoirelacoste** [comment]
hi @christpet  @lutangar @JalilArfaoui 

We have 2 options for the translation file keys:
- use natural keys: we will use the exact phrase in French
- use a catalog based on keys example: menu.link1 ...

The first option is probably more practical for translation work. On the English file we will see (thanks to the key) the sentence in French.
On the other hand, if we change the sentence in the content, it will also be necessary to change the key in every translation file to keep consistency...
Using a key catalog can also be tedious to maintain. If we choose this option I suggest to use as key the names of the components + a description word type: NotificationFooter.contribution

do you have opinions ?

**Comment by lutangar** [comment]
Here's are a few resource on best practices (or conventions) on translation keys out there :
- https://symfony.com/doc/4.2/best_practices/i18n.html#translation-keys
- https://shopify.dev/tutorials/develop-theme-localization-organize-translation-keys
- https://dev.xwiki.org/xwiki/bin/view/Community/L10N%20Conventions

I recommend using translation keys, and I would personally tend toward using `snake_cased` translation keys.

Overall, I think **Symfony** give  a sufficient guideline :
> Keys should always describe their purpose and not their location. For example, if a form has a field with the label “Username”, then a nice key would be label.username, not edit_form.label.username.

But if `i18next` suggest another conventions for naming the keys, just go for it!

**Comment by christpet** [comment]
Merci @gregoirelacoste agreed - the french should also be in the translation file(s). 

I agree with @lutangar, we should use a catalog based on keys. This way we can iterate more quickly on copy in both languages (and future ones) by only changing one file. 

Ditto to Johan's point on naming conventions, you can choose a convention and go for it!

**Comment by gregoirelacoste** [comment]
thanks to both of you, i will check these recommendations and suggest you something

**Comment by JalilArfaoui** [comment]
I agree with @lutangar too, but open to suggestion.

I like that `Keys should always describe their purpose and not their location` but it’s harder to do it right. I often see bad French translation because for example `post` can mean `message` or `send` depending on context, so you end up with a send button with text `message` … We need to use scopes and keys to be clear enough (is it a verb or a noun, …)

Also, I would argue that keys should be in English, not in French. First, because our whole codebase is in English, and also because a Russian translator might more comfortable with an English source than with a French one …

**Comment by gregoirelacoste** [comment]
I agree with you @JalilArfaoui 
I found this article with some good suggestion: https://phrase.com/blog/posts/ruby-lessons-learned-naming-and-managing-rails-i18n-keys/
and this one : https://lokalise.com/blog/translation-keys-naming-and-organizing/

It is difficult to be exhaustive without considering the location of the page. According to the lokalise article: _"namespaces can, for example, be named after different pages of your site or portions of the screen."_ I suggest using keys to describe the purpose in most cases, but for some of them like the internal content of a page, one key per location.

Please find here my suggestion (for extension only) : 
```JSON
{
  "global": {  //for common words, action and date
    //use keys in english
    "word":{
      "sock": "chaussette",
      "socks": "chaussettes"
    },
    "action": {
      "post": "Poster",
      "ask": "Demander"
    },
    "date": {
      "on_bulle": "Le {{date, DD/MM/YYYY}}"
    }
  },
  "layout": {
    "menu": {
      "my_account": "options"
    },
    "page_title": {
      "my_account": "Mon compte"
    }
  },
  "page_content": {
    "contributions": { // name of the page
      "disclaimer_no_post": "", // describe text in key
      "button_post_subtext": "", 
      "button_ask_subtext": ""
    }
  },
  "form": {
    "field_name": {      // for field, prefix with field plus name of field
      "label": "Votre nom",
      "placeholder": "Votre nom"
    },
    "button_preview_send": "Prévisualiser et publier", // button, prefix with button
  },
  "error": { 
    "form": {
      "require_field": "Ce champs est obligatoire"
    }
  }
}```

**Comment by lutangar** [comment]
Looks great! :+1:

**Comment by gregoirelacoste** [comment]
thanks !

**Comment by christpet** [comment]
Looks like excellent work @gregoirelacoste nice job! 

I am correct in assuming this is the file that needs to be translated correct? >> src/locales/en/extension.json 

If @JalilArfaoui gives the OK we can push this and I'll get started on translation.

**Comment by gregoirelacoste** [comment]
@christpet hi, thanks ! exactly, the file is here: src/locales/en/extension.json

**Comment by lutangar** [comment]
@christpet here's the link to the file on @gregoirelacoste branch:
https://github.com/dis-moi/extension/blob/feature/i18n/src/locales/en/extension.json

From the web interface, you could:
1. edit these files, 
2. create a new branch, 
3. Propose a PR on @gregoirelacoste branch

**Comment by christpet** [comment]
Thank you @lutangar that's perfect! I'll create a new branch 🙏
