### ISSUE TITLE
Modifier bulle qui s'affiche aux nouveaux utilisateurs sur page "Eclaireurs

### ISSUE THREAD

**Issue by KaliviArf** [dis-moi/extension#820]
A modifier quand le wording sur le site aura été modifié pour "sources de confiance" par "Vos éclaireurs" : 

Message actuel : 

Message pour les nouveaux :
- Lors de l'installation, nous vous avons présélectionné plusieurs contributeurs, plutôt consensuels. A vous de compléter et faire les choix définitifs !
- Une fois que vous avez choisi vos sources de confiance, vous pouvez revenir à votre navigation normale sur le web. Les informations et conseils de vos sources apparaitront directement sur les pages web que vous visitez.

**Modifs** 

Message pour les nouveaux :
- Lors de l'installation, nous vous avons présélectionné plusieurs **éclaireurs**, plutôt consensuels. A vous de compléter et faire **vos** choix définitifs !
- Une fois que vous **avez terminé,** vous pouvez revenir à votre navigation normale sur le web. Les informations et conseils de vos **éclaireurs** apparaitront directement sur les pages web que vous visitez.

![image](https://user-images.githubusercontent.com/78505335/110121241-6fed1a00-7dbe-11eb-8cae-277eded10314.png)

**Comment by KaliviArf** [comment]
@christpet

**Comment by MaartenLMEM** [comment]
@KaliviArf on peut faire ces modifications nous même dans le backoffice
Mais c est bien d'être Christian dans la boucle 
Ce sont des modifications mineures, donc pas de validation nécessaire, informer est suffisant.
Pour moi c est bon.
J aurais juste une préférence pour "les conseils et infos de vis éclaireurs" sur la formule plus longue "informations et conseils de".
Au fait, pour l instant il n y a pas de gras ou autre mise en forme dans contrib.

**Comment by KaliviArf** [comment]
Done @MaartenLMEM @christpet
