### ISSUE TITLE
Make the translation of the "profiles" work on the storybook

### ISSUE THREAD

**Issue by gregoirelacoste** [dis-moi/extension#825]
The issue: we have to use 2 instances of i18next (extension and profile) in the same time on storybook. But it doesn't work. Only one at a time.
I suggest to keep only one I18next config file inside the locales root folder and use the same file for both (extension and profiles) app. 
We will use name spaces to handle the right translation inside the 2 apps. 

are you ok @lutangar @JalilArfaoui ?

**Comment by lutangar** [comment]
If you're speaking about `src/app/profiles/i18n/index.ts` these files are already including all translations right? So it's already almost the case.
You  shouldn't do that refactor *just* because of Storybook though. But it might bring some clues on a better design anyway :)

**Comment by christpet** [comment]
Right, agreed with @lutangar that having Storybook in two languages is not in our requirements right now. That said, it definitely sounds like a better design to do things the way you describe, and there may be benefits in the future. I would suggest going forward with this change @gregoirelacoste.

**Comment by gregoirelacoste** [comment]
@lutangar @christpet thx
src/app/profiles/i18n/index.ts and src/app/content/i18n/index.ts include the translation and are almost the same, idem for format.ts. So refactor this could make an organization more coherent. 
More over, i think the issue with storybook i quiet big, please look the result : 
![image](https://user-images.githubusercontent.com/60737012/110813254-9f04ff00-8288-11eb-8ee5-329d64238948.png)
These are the translation files that now displaying the text, so we no longer see the real text on the storybook.

I proceed ?

**Comment by lutangar** [comment]
Sure, I think we'd better understand possible impacts (if any) once is done.

**Comment by christpet** [comment]
Yes go for it @gregoirelacoste !
