### ISSUE TITLE
Matomo : can't extract more than 1 months of data

### ISSUE THREAD

**Issue by zhinu** [dis-moi/extension#826]
**Describe the bug**
When trying to extract a large chunk of data, I am met with an error stating "The archiving of your reports hasn't been executed recently, learn more about how to generate your reports."

**To Reproduce**
1. Go to stats.lmem.net
2. Choose a data type to extract (i.e. visitors/UserIds)
3. Select a time period greater than a months (i.e. a year)
4. See error and no data showing

**Expected behavior**
There should be some data there and the possibility to export them.

**Screenshots**
![image](https://user-images.githubusercontent.com/75084558/110649222-af9a7400-81b9-11eb-84f9-ab67696b5ba7.png)

**Additional context**
When looking at the error in "piwik_archive_error.log", I get this message :  Got invalid response from API request: ?module=API&method=API.get&idSite=6&period=year&date=last7&format=php&trigger=archivephp. The response was empty. This usually means a server error. A solution to this error is generally to increase the value of 'memory_limit' in your php.ini file.  For more information and the error message please check in your PHP CLI error log file. As this core:archive command triggers PHP processes over the CLI, you can find where PHP CLI logs are stored by running this command: php -i | grep error_log

So I looked into increasing the php "memory_limit" to 512M, unfortunately, gandi.net's simple hosting doesn't not allow for our plan to have this var modified so it is stuck to 128M.
It is likely that the error stems from there however it is yet to be proven.

**Comment by christpet** [comment]
@zhinu I saw you had discussed this on slack but wanted to be sure it doesn't get lost... can we get around this by just exporting 1 month at a time?

**Comment by zhinu** [comment]
@christpet Theoretically yes. 
However, to extract data such as who didn't login in for 2 months, it becomes tricky.

**Comment by christpet** [comment]
Agreed this is tricky @zhinu. Do you know is there a user ID number we can use to identify individual users (anonymously) across time?

**Comment by zhinu** [comment]
So increasing the PHP memory_limit to 512M solved the issue
