### ISSUE TITLE
Modifier URL https://www.dismoi.io/sources/

### ISSUE THREAD

**Issue by KaliviArf** [dis-moi/extension#827]
**Modifier URL https://www.dismoi.io/sources/** 

en https://www.dismoi.io/voseclaireurs/

suite changement du menu opéré sur DisMoi.io

![image](https://user-images.githubusercontent.com/78505335/110911788-6b22eb80-8313-11eb-91cd-702d760ec4fe.png)

**Comment by KaliviArf** [comment]
@christpet @antoinewolff

**Comment by MaartenLMEM** [comment]
rather /eclaireurs than /voseclaireurs

**Comment by antoinewolff** [comment]
@lutangar, @JalilArfaoui : When I try to change the [sources page](https://www.dismoi.io/sources/) slug  for from `/sources` to `/eclaireurs` the `dismoi-profiler-app` is not working anymore. 

<img width="1161" alt="Capture d’écran 2021-03-15 à 09 21 19" src="https://user-images.githubusercontent.com/12514460/111126079-93f4ec00-8572-11eb-9719-ae758162bcfd.png">

It seems that there is references to this URL in the script hosted here https://profiles.dismoi.io/js/profiles.bundle.js?ver=0.12

<img width="1161" alt="Capture d’écran 2021-03-15 à 09 39 55" src="https://user-images.githubusercontent.com/12514460/111126088-96efdc80-8572-11eb-958d-723887731720.png">

After a quick look, I didn't find on which repository this script is maintained.

**Comment by lutangar** [comment]
> rather /eclaireurs than /voseclaireurs

Yeah, or `/vos-eclaireurs` at least.

> When I try to change the sources page slug for from /sources to /eclaireurs the dismoi-profiler-app is not working anymore.
Yes, this is expected. These URLs must be changed here in the extension:
https://github.com/dis-moi/extension/search?q=%27%2Fsources%27

Can you manage? Or do you need some help? @gregoirelacoste might be the right man for the job!

**Comment by antoinewolff** [comment]
@lutangar : Thks for the informations. `/eclaireurs` is nicer from my point of view (less is more).
@gregoirelacoste : Your help is welcome cause I prefer to do it with synchronicity : you will push the update on extension while I'm updating the database on the website. We can do this tomorow if you want ?

**Comment by gregoirelacoste** [comment]
@antoinewolff no problem, we can do that tomorow morning

**Comment by KaliviArf** [comment]
@antoinewolff @lutangar @gregoirelacoste nous diffusons demain matin une communication = dans le communiqué de presse préparé mon lien pointe vers l'URL "https://www.dismoi.io/sources/" = pouvez vous faire en sorte de rediriger ? ou bien (mieux ;) pouvez-vous effectuer les changements avant ce soir pour que je puisse mettre la nouvelle url dans la communication qui partira demain matin ?

**Comment by gregoirelacoste** [comment]
@KaliviArf mettre en prod le jour même d'un envoi de communiqué de presse, n'est-ce pas trop risqué ?

**Comment by KaliviArf** [comment]
@gregoirelacoste  oui je confirme... Donc soit aujourd'hui ou fin de semaine du coup... :)

**Comment by gregoirelacoste** [comment]
@KaliviArf i'm working on it right now. @antoinewolff @lutangar I let you decide if apply this change in prod is possible. I use /eclaireurs ?

**Comment by gregoirelacoste** [comment]
@KaliviArf je ne peux pas t'ajouter en reviewers, mais je t'invite à surveiller l'évolution de ce ticket sur la PR : #834
