### ISSUE TITLE
Sentry is unusable: Fix or replace

### ISSUE THREAD

**Issue by christpet** [dis-moi/extension#838]
Problem:
Sentry is supposed to help us notice and fix bugs in the extension. Right now, it is throwing so much noise that it is unusable.

Question to answer:
How do we fix Sentry? What is the cost?
What is the cost of replacing Sentry?

**Comment by lutangar** [comment]
I actually found the related issue there:
https://github.com/dis-moi/backend/issues/308

**Comment by JalilArfaoui** [comment]
Replacing Sentry won’t do any good here … If we want to hear the signal, we have to lower the noise …

I’ll try to tackle https://github.com/dis-moi/backend/issues/308 this week …

**Comment by christpet** [comment]
Fair enough @JalilArfaoui it is a useful tool to have, so let's do the minimum to make it work. Let's keep it focused on https://github.com/dis-moi/backend/issues/308 ... this is not super top priority, but would be a nice-to-have in the next few weeks.

**Comment by christpet** [comment]
Closing this in favor of https://github.com/dis-moi/backend/issues/308
