### ISSUE TITLE
User account

### ISSUE THREAD

**Issue by lutangar** [dis-moi/extension#843]
> depends on https://github.com/dis-moi/backend/issues/324

**Comment by christpet** [comment]
Nice. This is specifically user authentication for users who want to post a contribution from the extension, correct?

**Comment by lutangar** [comment]
We might need todo some product design in order to make this work, let's track this here.

**Comment by christpet** [comment]
Ah so this is referring to user accounts through all of the different sides of the product, as you mentioned @lutangar in https://github.com/dis-moi/backend/issues/324 : 

- Contribute from the extension
- Bulk contribution
- Contribution interface

So this is in the "product design" phase and needs technical specifications. I'll assign it to myself to push to break it down into smaller units.

**Comment by lutangar** [comment]
> __@MaartenLMEM saide in https://github.com/dis-moi/backend/issues/324__
> About the solution : Do we really need authentification in extension ?
In those usecases, as extension user who want to contibute, I can authenticate in a webpage directly.
Because all really contextual informations (current webpage, even the message I started to draft...) can be saved without authentification a webpage.

Good question, let's discuss about this!
