### ISSUE TITLE
404 error after installing the extension

### ISSUE THREAD

**Issue by gregoirelacoste** [dis-moi/extension#847]
**Describe the bug**
404 error After installing the extension from chrome or firefox, redirection is wrong. User is redirected to /sources?pk_campaign=installed instead of /eclaireurs

**To Reproduce**
1. Install app from store
2. Valid
3. See the 404 error

**Expected behavior**
See all the eclarieurs page

**Screenshots**
![image](https://user-images.githubusercontent.com/60737012/111318860-bb78b100-8665-11eb-8159-40b1bb857857.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser chrome and firefox
 - Last version

**Additional context**
Can't find where specify this link

**Comment by gregoirelacoste** [comment]
@antoinewolff try this link : https://www.dismoi.io/sources?pk_campaign=installed

**Comment by gregoirelacoste** [comment]
@antoinewolff handle the redirection from wordpress but it would be nice to change this link

**Comment by christpet** [comment]
Thank you for flagging this @gregoirelacoste , just heard from Antoine that he is on it.

**Comment by antoinewolff** [comment]
Done !

`https://www.dismoi.io/sources?pk_campaign=installed` is redirected to `https://www.dismoi.io/eclaireurs/?pk_campaign=installed`

I think that the "/" is added by wordpress... I don't see how I can remove it. I think there is no difference on the interpretation of the two url.

**Comment by antoinewolff** [comment]
@gregoirelacoste : I let you close this issue.

**Comment by lutangar** [comment]
> handle the redirection from wordpress but it would be nice to change this link

I agree. This is not truly fix as long as we are pointing at the wrong URL. 
If it's happening in production, we probably just need to publish a new version of the extension to be in sync with profiles app recent changes.

**Comment by gregoirelacoste** [comment]
I will waiting for the new release of the extension before close this issue

**Comment by lutangar** [comment]
There was a release 4 days ago :
https://github.com/dis-moi/extension/releases

Is this still relevant?

**Comment by gregoirelacoste** [comment]
@lutangar I just tested, it's good it's fixed
