### ISSUE TITLE
If there are more than 2 notices on a page, they are invisible

### ISSUE THREAD

**Issue by MaartenLMEM** [dis-moi/extension#850]
**Describe the feature/improvement**
Let see that there are more than 2 notices on a same page and give access to them

**Target user**
DisMoi addon users

**Fill in the following areas if you have the time...**

**User stories**
How will the user experience this feature/improvement?
1. The visit a page where there a 3 (or more) notices matching
2. User can see the two first preview, and I can see that there are others 

**Technical implementation notes**
Display all bubbles and add a scrollbar

**Additional context**
It s also an issue for a contributor whose contributions are invisible, which is frustrating (got a mail about this case (see [this page](https://www.sephora.fr/shop/soin-visage/demaquillant-et-nettoyant-c7633/)) from Ethik'do wher bubble 1524 is not visible.
![image](https://user-images.githubusercontent.com/7824485/111503380-fe5e8580-8746-11eb-83c5-378e7267404a.png)

**Comment by christpet** [comment]
Ah this is an interesting one, thank you @MaartenLMEM. Since we are getting complaints about it, it's a good idea to bump it up in priority. 

Maybe @gregoirelacoste you can take a look at this when you are finished with #837 ?

**Comment by christpet** [comment]
Maybe @newick can weigh in here as well, do we have a scroll design ready for inside the extension?

**Comment by newick** [comment]
@christpet scrollbar is default browser one. 
I can go on this one before the end of the week.

**Comment by MaartenLMEM** [comment]
Sorry but actually the solution I suggested (scrollbar) seems me not enough. 
Because as an web user, if you I don't see a part of the third item, scrollbar will probably be not enough to make it clear to my mind there is a third item.  
Well you may say : it's better to have a scrollbar than nothing. And let's see how people deal with it.

**Comment by gregoirelacoste** [comment]
@MaartenLMEM  Firstly, without going through the UI, announcing the number of bubbles on the page + scroll message, might be enough?

**Comment by MaartenLMEM** [comment]
I don't know what you mean by "scroll message". 
Also @christpet  and Marco are better qualified than me to answer this question.
I can give insight about past experience and choices.

**Comment by newick** [comment]
I think that some quick wins could be a scrollbar, and work with @coffeeandpixel about infos (which is a great idea @gregoirelacoste!)

**Comment by gregoirelacoste** [comment]
@MaartenLMEM sorry it wasn't clear. I meant a label in just abover "poster" btn, which say : "scroll to see more bulles". It appear only if there is more than 2 bulles on this page, it's a quick win. 
thx @newick

**Comment by christpet** [comment]
Agreed @gregoirelacoste and @newick , that's a good quick win. We can iterate from there. 

@newick let's stick with the default browser scroll bar, and you can use your judgment to put the "scroll to see more" label where it works best.

So (please correct me if I'm wrong) the next steps are:
1. @newick to integrate the interface (after he is done with the onboarding integration)
2. @gregoirelacoste to implement the logic so that this appears when there are 3+ bulles (after onboarding is done as well)

Sound good? :)

**Comment by gregoirelacoste** [comment]
@christpet perfect for me

**Comment by MaartenLMEM** [comment]
good job !
![image](https://user-images.githubusercontent.com/7824485/116299115-923b5c80-a79d-11eb-95a3-104a319529c0.png)
