### ISSUE TITLE
Make the contributors js app works with english version of the website

### ISSUE THREAD

**Issue by antoinewolff** [dis-moi/extension#852]
**Describe the feature/improvement**
- 1srt and urgent : The contributors js app must be displayed on the URL https://www.dismoi.io/en/guides/
- 2nd : We must thinks about the contributor's profile pages translation strategy and release it.

**Target user**
The website visitors

**Comment by gregoirelacoste** [comment]
for the second i will catch the en/ path and use it with  i18n.changeLanguage(lng) to display english
@antoinewolff I need all the new "en" URL to set up the routes

**Comment by christpet** [comment]
@gregoirelacoste this is a good next one to focus on - looks like "/en/guides" is redirecting to "/eclaireurs" currently.

**Comment by gregoirelacoste** [comment]
@christpet ok, i do that tomorrow

**Comment by gregoirelacoste** [comment]
update status here : https://github.com/dis-moi/extension/pull/886#issuecomment-812541336

**Comment by MaartenLMEM** [comment]
@prk-dismoi can y ou have a look if it works from your home ?

**Comment by prk-dismoi** [comment]
Redirects here for me: https://www.dismoi.io/eclaireurs. All seems to work fine on the page (in english)

**Comment by prk-dismoi** [comment]
![image](https://user-images.githubusercontent.com/80406294/116704984-5508e180-a9cc-11eb-8f31-ebcc805efa3a.png)
