### ISSUE TITLE
"Invalid date" label diplayed on all "contribution phares" shown on all profile pages

### ISSUE THREAD

**Issue by MaartenLMEM** [dis-moi/extension#856]
**Describe the bug**
instead of creation date there is writen "invalid date"
It working on local and staging but not in prod.
Other dates for "last contribution" is working fine

**To Reproduce**
- Go to any profil page
- scroll to contribution phares examples

**Expected behavior**
creation date

**Screenshots**
![image](https://user-images.githubusercontent.com/7824485/111643453-43de8980-87ff-11eb-8391-660d13e091e7.png)
![image](https://user-images.githubusercontent.com/7824485/111643779-83a57100-87ff-11eb-9628-af1f6b26506a.png)

**Desktop (please complete the following information):**
 firefox and chrome

**Extension**
- Version 3.61.0

**Comment by gregoirelacoste** [comment]
@JalilArfaoui @lutangar I think there is an issue with notice API during Contributor get request.
Prod received only form notices.bulles.fr/api/v3/ : 
```
{
	"0": {
		"sort": 0,
		"exampleMatchingUrl": "https://www.backmarket.fr/",
		"noticeId": 423,
		"noticeUrl": "https://notices.bulles.fr/api/v3/notices/423",
		"screenshot": "https://notices.bulles.fr/uploads/notice_screenshots/ei7KcNdeU0.PNG"
	}
}
```

Staging receive from https://staging-notices.bulles.fr/api/v3/ : 
```
{
	"0": {
		"id": 423,
		"url": "https://staging-notices.bulles.fr/api/v3/notices/423",
		"message": "<p>Mieux vaut acheter votre produit reconditionné ailleurs. Derrière la bonne image de marque de la plus grande place de marché du reconditionné en France, très nombreux sont les clients de Back Market à se plaindre sur le web : faible autonomie de batterie, accessoires défaillant, écran abîmé, connectivité, service-après vente, etc. <br />\r\n- Pour un smartphone reconditionné, orientez vous plutôt vers <a   href=\"https://www.lmem.net/smaaart-smartphone-reconditionne/?utm_medium=Dismoi_extension_navigateur\" target=\"_blank\" rel=\"noopener noreferrer\">la marque Smaaart</a> ou directement vers les marques elles-mêmes, par exemple Apple Refurbish.<br />\r\n- Pour les autres produits, privilégiez les produits vendus par le fabriquant lui-même, sur BackMarket (il est parfois signalé par la mention &quot;Boutique Officielle&quot; sous l'image du produit) ou sur le site de la marque elle-même.<br />\r\n<a   href=\"https://www.lmem.net/back-market-achat-risque/?utm_medium=Dismoi_extension_navigateur\" target=\"_blank\" rel=\"noopener noreferrer\">En savoir plus</a></p>",
		"strippedMessage": "<p>Mieux vaut acheter votre produit reconditionné ailleurs. Derrière la bonne image de marque de la plus grande place de marché du reconditionné en France, très nombreux sont les clients de Back Market à se plaindre sur le web : faible autonomie de batterie, accessoires défaillant, écran abîmé, connectivité, service-après vente, etc. <br />\r\n- Pour un smartphone reconditionné, orientez vous plutôt vers la marque Smaaart ou directement vers les marques elles-mêmes, par exemple Apple Refurbish.<br />\r\n- Pour les autres produits, privilégiez les produits vendus par le fabriquant lui-même, sur BackMarket (il est parfois signalé par la mention \"Boutique Officielle\" sous l'image du produit) ou sur le site de la marque elle-même.<br />\r\nEn savoir plus</p>",
		"visibility": "public",
		"exampleUrl": "https://www.backmarket.fr/",
		"exampleMatchingUrl": "https://www.backmarket.fr/",
		"screenshot": "https://staging-notices.bulles.fr/uploads/notice_screenshots/ei7KcNdeU0.PNG",
		"ratings": {
			"likes": 9,
			"dislikes": 2
		},
		"created": "2019-12-03T16:52:30+01:00",
		"modified": "2020-08-10T13:50:08+02:00",
		"contributorId": 16,
		"relayersIds": [
			24,
			25,
			32
		]
	}
}
```
not knowing the backend yet, I would like some help to finalize this

**Comment by lutangar** [comment]
I can take it from here @gregoirelacoste 
Could you paste here both (staging/prod) GET URL  you're mentioning here plz?

**Comment by gregoirelacoste** [comment]
@lutangar 
GET which retrieve the pined notices for lmem :
staging: https://staging-notices.bulles.fr/api/v3/contributors/16
prod: https://notices.bulles.fr/api/v3/contributors/16

**Comment by lutangar** [comment]
Nice catch,  what you found out on the `pinnedNotices` data structured was actually fixed in.... december 2020
> see https://github.com/dis-moi/backend/pull/298

But the actual running version of the backend age back to.... :scream: november the 10th. 
This is crazy and should never happens again. I'm going to deploy the backend and hope #313 will go forward with an automated process!

**Comment by lutangar** [comment]
Fixed by deploying new backend version.

**Comment by christpet** [comment]
Confirmed fixed in staging-firefox 👍
