### ISSUE TITLE
Invalid Date on featured notice

### ISSUE THREAD

**Issue by gregoirelacoste** [dis-moi/extension#860]
**Describe the bug**
The date are all invalid for the featured notices on profiles app for an unknown reason. 
It working on local but not in prod.
Other dates for "last contribution" is working fine

**To Reproduce**
1. Go to https://www.dismoi.io/eclaireurs/16/Le-Meme-en-Mieux
2. First featured notice
3. Bottom

**Expected behavior**
Featured notices dates work the same as last contribution notices dates

**Screenshots**
![image](https://user-images.githubusercontent.com/60737012/111756002-0418b000-889a-11eb-9b88-08599b0b52ff.png)

**Additional context**
Bug only in prod

**Comment by MaartenLMEM** [comment]
looks like we discovered it same day https://github.com/dis-moi/extension/issues/856

**Comment by gregoirelacoste** [comment]
@MaartenLMEM indeed, i work on it today, i close this one and l take yours as a reference
