### ISSUE TITLE
Chrome extension blocked on Chloé and Maarten's computers and probably others

### ISSUE THREAD

**Issue by MaartenLMEM** [dis-moi/extension#861]
**Describe the bug**
On Chloé's computer on every page, DisMoi is grey : no notice, no interaction possible. 
It's possible she had same problem on other computer, but not sure.

**Vidéo**
This Vidéo shows bug but also informations from extension background.
It has been recorded during our call : https://drive.google.com/file/d/1kqcqnqXR5raQYVGhpUAObLNK6Dc7tUTC/view

**To Reproduce**
I don't know

**Desktop):**
 - OS: Windows
 - Browser : Chrome 
 - Version : 89 0.4389 90

**Extension**
- Version : 3.61
- Installed from store
- Installation date : don't know, probably recently
It's a new computer she just bought, refurbed.

**Comment by MaartenLMEM** [comment]
Sorry, the video has been stopped just before it shows background :-/

**Comment by MaartenLMEM** [comment]
Good news @christpet I could reproduce the problem on my computer.
I am pretty confident Chloé met same as I did. 
[Here is the video]( https://drive.google.com/file/d/1ln_OSSynEQHmTI3aq7cXFRBYUESr9ZfV/view)
To summarize what probably happend : 
1. Backend had a problem
2. Extension received error 524
3. Extension is blocked 

Of course I can't be 100% sure about step 1. Another cause could be that my computer entered into standby during lunch. But It happens everyday without any problem, so I am quite sure this is not the cause.

**Comment by MaartenLMEM** [comment]
Here is a [video on Firefox ](https://drive.google.com/file/d/1lhgv-wLCddcQ7MgIKGEMgKQMK-lFO_tm/view): same problem, probably same reason as previouw video on chrome

**Comment by MaartenLMEM** [comment]
Some news :
- This morning I opened my browser and the problem was still there (I did not switch off my computeur since yesterday)
- So I restarted my computer. Then it was ok.
**Conclusion** : For people who don't switch off their computeur but just enter it into standby mode, their add on is likely to be blocked for an indefinite period.

**Comment by christpet** [comment]
Thanks for the great work @MaartenLMEM to reproduce and narrow it down... it looks like you're right, it seems like there's an issue coming from the backend. I will ping @JalilArfaoui to look into this when you're able 🙏

**Comment by lutangar** [comment]
No matter what's issue the extension is running into it should be able to gracefully handle it.

**Comment by christpet** [comment]
@JalilArfaoui do you have time this week to look into this?

**Comment by christpet** [comment]
Ah okay, so it looks like we're getting an idea of what is causing all these problems. Can we come up with a plan to address it?

Looks like all these issues are connected:
- #257 
- https://github.com/dis-moi/backend/issues/335
- #801 
- #861
- https://github.com/dis-moi/backend/issues/335 
- others?

On the plus side, if we can fix this then alllll these issues will get completed 😺 

@JalilArfaoui @lutangar @julienadamcom what do you think is needed here? This is a bit out of my depth to handle, I'll need your help to figure out a solution - even if it is XL!

**Comment by JalilArfaoui** [comment]
Background process crashes with :

![image](https://user-images.githubusercontent.com/3037833/114731379-fee83d00-9d41-11eb-9ffb-157e865cdee5.png)

and never recover

**Comment by JalilArfaoui** [comment]
PR #915 should fix at least the scenario I could reproduce : Now, the extension will continue to try fetching contributors and matching contexts indefinitely (max 10 minutes between retries)

But user will still have a «dead UI» in the meantime : grey icon and nothing happens. We should really start implementing #801, starting IMHO with something like a red browser icon as long as we’re having trouble talking with the backend …

**Comment by JalilArfaoui** [comment]
And also we could come up with a better and more global network handling mechanism, for example not retrying anything until we can ping the backend …

**Comment by MaartenLMEM** [comment]
OK  #801 is set as a priority 

> And also we could come up with a better and more global network handling mechanism, for example not retrying anything until we can ping the backend …

Ok I like this path, but I do not see precisly what it refers to. 
Did you already identify a specific case where it is retrying without any chance to succeed ? 
Or is it a general guess ? If it is a guess, do you have any idea of this kind o event frequency ?

**Comment by MaartenLMEM** [comment]
Notes from my call with Jalil a few minutes ago 

Fix apposé ici : tant que que t'as pas réussi à fletcher sur matching context et contributeur, tu continues d'esssayer avec ralentissement progressif des essais avec un max de 10 minutes

_Pour la suite, c'est quoi _retry anything_ ? 
_ C'est une sorte d'url health dans le BO qui serait pinger en cas de problème : tant que c'est down l'extension ne fait plus de requêtes. Actuellement le mécanisme de retry a été changé pour s'adpater aux coupures plus longues et aux 524 (au bout de 10 essais l'extension se crachait)
=> Maarten created #924 

De même, il faudrait une carte sur "si l'extension vais chercher un notice" et que j'ai pas d'appel réseau. 
=> Jalil will create issue about this last point.
