### ISSUE TITLE
Make storybook use assets

### ISSUE THREAD

**Issue by gregoirelacoste** [dis-moi/extension#865]
**Describe the feature/improvement**
Storybook don't handle for moment, make it possible

**Target user**
Developers, UI

**Technical implementation notes**
add `-s ./src/assets` to package json storybook script

**Comment by MaartenLMEM** [comment]
@newick if this is ok please move it to last column

**Comment by newick** [comment]
@MaartenLMEM i don't feel confortable to move something I didn't interact with.
How do I know if it has been deployed?
I think if it has the `deployed` tag it should be ok, but how to know for sure?

@lutangar any idea of how to make something clear?
