### ISSUE TITLE
404 on "proding-profiles.dismoi.io/eclaireurs"

### ISSUE THREAD

**Issue by christpet** [dis-moi/extension#870]
**Describe the bug**
"The requested URL was not found" when navigating to https://proding-profiles.dismoi.io/eclaireurs?pk_campaign=installed directly after installing the Firefox Proding addon, version 3.67.2

**To Reproduce**
1. Download the Firefox Proding version from the latest release version in GitHub
2. Drag the file into Firefox (with no other Dismoi version installed) and install the addon
3. See the 404

**Expected behavior**
Should show the "Profiles" page with all the contributors

**Screenshots**
![image](https://user-images.githubusercontent.com/32476396/112358138-56116980-8cd0-11eb-8cce-7b9dc1230931.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Firefox

**Extension**
- Version 3.67.2
- Installation date today

**Additional context**
No other browser extensions installed.

I don't think this is super complicated but need to address it in case this problem replicates on the production server.

**Comment by christpet** [comment]
Pinging @lutangar @gregoirelacoste @felix-lambert - which one of you would like to take this? :)

**Comment by gregoirelacoste** [comment]
@christpet i do

**Comment by lutangar** [comment]
@gregoirelacoste I saw you reactivate the `proding` profiles app in __Clever Cloud__, good  first step :+1: 
Don't remember which domain is supposed to be linked to this app tho' -_-

**Comment by christpet** [comment]
@gregoirelacoste any update here? I'm still getting the 404 in the latest version - I want to make sure this doesn't happen in prod!

**Comment by gregoirelacoste** [comment]
@christpet it's in progress, but I already confirm that there is no 404 error in prod for this url : https://www.dismoi.io/eclaireurs/?pk_campaign=installed

**Comment by christpet** [comment]
Ok - in current production environment the 404 is not happening. That is good. 

I want to make sure that when we push the current version that is in Firefox Proding https://github.com/dis-moi/extension/releases/tag/v3.69.1 this problem doesn't reproduce in production

**Comment by gregoirelacoste** [comment]
@christpet all is working on staging, but for now I can't understand why nothing is working on proding... let me one hour before push on prod
