### ISSUE TITLE
Language detection bugs

### ISSUE THREAD

**Issue by coffeeandpixel** [dis-moi/extension#883]
Hello, I've a problem on the DisMoi HP.
In the French homepage, by clicking on the "vos eclaireurs" menu I am redirected to the contributors page but in English. Moreover, the "following" button is translated as "Subscribers", a bit strange ... (see screenshot)

Can you verify?
Thank you

![Screenshot 2021-03-29 at 15 42 26](https://user-images.githubusercontent.com/16020438/112845920-b542f580-90a5-11eb-8353-cf37f922fdac.png)

**Comment by christpet** [comment]
@coffeeandpixel thanks, we have noted the "subscribers" issue.

could you tell us the language of your browser? If it's anything except French then this might be the correct behavior, correct me if I'm wrong @gregoirelacoste

**Comment by coffeeandpixel** [comment]
@gregoirelacoste @christpet If we don't use geolocation, can we have the same function on all pages? in order to see all the pages of the site in the same language.

**Comment by gregoirelacoste** [comment]
@coffeeandpixel i confirm, it's because your browser is in english. You use geolocation only on extension and profiles app (eclaireurs and notices page) but I don't think that there is geoloc feature on the website @antoinewolff ?

**Comment by antoinewolff** [comment]
There are the options offered by WPML the plugins : 
<img width="1003" alt="Capture d’écran 2021-03-29 à 16 42 01" src="https://user-images.githubusercontent.com/12514460/112854177-e0c9de00-90ad-11eb-8448-ae936d03b7e4.png">

**Comment by gregoirelacoste** [comment]
on extension and profiles app side our politic will be: 
- url is source of truth to determine the language
- if browser language is detected and exist in translate file > redirect to the right url
- if not > fallback language === EN

could we do the same on the website ?
