### ISSUE TITLE
Youtube player display issue

### ISSUE THREAD

**Issue by gregoirelacoste** [dis-moi/extension#888]
Notice tested : Bulle (#1538)
Page : https://www.lemonde.fr/les-decodeurs/article/2020/09/24/5g-le-vrai-le-faux-et-ce-qu-on-ne-sait-pas-encore_6053447_4355770.html

**Prod layout (current)**
![image](https://user-images.githubusercontent.com/7824485/112954006-48c80500-913e-11eb-9cd1-24f278af369b.png)

**Proding layout :** 
![image](https://user-images.githubusercontent.com/7824485/112953614-ec64e580-913d-11eb-8185-fb39c9842ada.png)

_Originally posted by @MaartenLMEM in https://github.com/dis-moi/extension/issues/759#issuecomment-810003639_

and https://github.com/dis-moi/extension/issues/759#issuecomment-810005898

**Comment by gregoirelacoste** [comment]
@MaartenLMEM @christpet 
This problem comes from the way videos are integrated to a bubble from the backoffice.

Currently the only method to embed the video is the most simple: just copy past the URL. Like : `https://www.youtube.com/watch?v=dQw4w9WgXcQ`

But i see in Backoffice this: `<a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ">Voir la vidéo</a>`
The regex which recognize youtube link don't work with `<a href="`...
Result is something like: `&utm_medium=Dismoi_extension_navigateur" target="_blank" rel="noopener noreferrer">Voir la vidéo ` (depend the link)

I suggest two things:
- _Important_: Improve the regex to recognize and delete HTML tags `<a href`> it's important because It will recognize all the old videos contributions without change the text manualy
- _Optional_: Improve backoffice to put new field: VIDEO. With following label: `just put the url of the youtube video`

what do you think ?

**Comment by MaartenLMEM** [comment]
>     * _Important_: Improve the regex to recognize and delete HTML tags `<a href`> it's important because It will recognize all the old videos contributions without change the text manualy

We use <a href> in many cases not only with videos. Also we can't ask contributors to use one way of coding for Youtube, and another code for other links (vidéo or not). There will be errors. Also in some case, contributor want to put a link to a vidéo to explain a detail, thus not display a preview. 

So I agree with this proposal if it allows us to use both ways of coding ine the future : <href="...> and youtube url direclty. 

>     * _Optional_: Improve backoffice to put new field: VIDEO. With following label: `just put the url of the youtube video`

Too complex for a nice to have

More generally, this feature was supposed to be a quick win. If takes more time, see with @christpet if it is still to do.

**Comment by christpet** [comment]
> * _Important_: Improve the regex to recognize and delete HTML tags `<a href`> it's important because It will recognize all the old videos contributions without change the text manualy

From what I understand, we could make this option work if and only if the "<a href>" is recognized and deleted ONLY for YouTube videos. Would that give us the result we want @gregoirelacoste ? What is the main problem that is causing the issue?

To clarify, the desired result is one where:
- YouTube videos show up as embedded
- All other links show up as simple hyperlinks

**Comment by gregoirelacoste** [comment]
@christpet the main problem come from the regex which don't match with <a href... so exactly, the goal is: display video instead of link only for youtube video links

**Comment by christpet** [comment]
Ok awesome. English version stuff is priority but if you can do this next that would be great @gregoirelacoste !

**Comment by MaartenLMEM** [comment]
@gregoirelacoste Solution developped generates a new problem. 
See screenshot below : the text is tronqué
The right solution is to keep links as anchors when they are anchors. 

In any cas, vie embedded should be after the whole text.

Sorry this complexity has not been forseen.

![image](https://user-images.githubusercontent.com/7824485/116297276-63bc8200-a79b-11eb-9f42-4ae37523a061.png)

**Comment by MaartenLMEM** [comment]
Working well but little new issue here  :
if I click on thumb up, video displayed disappear. 
Let s push it in prod and tackle this little issue in another release.
