### ISSUE TITLE
Change of link on contributor boxes

### ISSUE THREAD

**Issue by coffeeandpixel** [dis-moi/extension#890]
In the contributors' boxes (on any page where they are showed. EX: https://www.dismoi.io/eclaireurs/ ) we have to replace the text of the link "Voir ses contributions" by "Voir un example".
By modifying the text, the action must also change:

I click on “Voir un example”

** -----> IF HAVE ALREADY INSTALLED THE DISMOI EXTENSION:**

**CASE 1: I am a subscriber to the contributor**
I have just redirected to the example page (on target = "_ blank")

**CASE 2: I am not a subscriber to the contributor**
- A pop-in opens which explains to me that I have to follow the contributor to see his example.
- I click on follow and see the example
- I have just redirected to the example page (target = "_ blank")

** -----> IF HAVEN'T INSTALLED THE DISMOI EXTENSION:**

- A pop-in opens which explains to me that I have to install the extension.
- I install the browser extension

**FROM HERE, THE PROCESS IS AS ALREADY SEEN ABOVE**

**CASE 1: I am a subscriber to the contributor**
I have just redirected to the example page (on target = "_ blank")

**CASE 2: I am not a subscriber to the contributor**
- A pop-in opens which explains to me that I have to follow the contributor to see his example.
- I click on follow and see the example
- I have just redirected to the example page (target = "_ blank")

[MOCKUP](https://xd.adobe.com/view/dfae0acd-b1e5-4b31-8496-5bcd7c64f76a-8afd/)

**Comment by coffeeandpixel** [comment]
PS: today for those who want to install the extension and are on an unsupported browser (example: safari) there is a pop-in that invites them to use another browser. clearly this function must remain intact

**Comment by gregoirelacoste** [comment]
I just draw a summary schema.
I have a question @coffeeandpixel why redirect to a blank page to see the contribution img ? why not display it in a modal inside the same page ?
![image](https://user-images.githubusercontent.com/60737012/114363713-fb558a00-9b78-11eb-8df0-6cfa9df42e10.png)

**Comment by MaartenLMEM** [comment]
@coffeeandpixel What about a label : "Voir un exemple réel" ?

**Comment by gregoirelacoste** [comment]
>  @coffeeandpixel why redirect to a blank page to see the contribution img ?

@coffeeandpixel i already have the answer ;)

**Comment by gregoirelacoste** [comment]
@MaartenLMEM in english "See a real example" ?

**Comment by MaartenLMEM** [comment]
@gregoirelacoste je viens de tester voici mes remarques :
- Le mécanisme d’abonnement + ouverture automatique qu'a proposé Marco génère un petit bug technique : si je clique sur suivre ça m'ouvre la page cible mais la bulle ne se déclenche. 
Donc je te proposer de reprendre plutôt le mécanisme complètement identique qui existe actuellement sur les pages profils.
- Il y a un petite erreur sur la label du bouton (cela devrait être "suivre [contributeur" et non "installer DisMoi")

**Comment by MaartenLMEM** [comment]
Label first modal :  
Veuillez suivre Colibri écolo pour voir ses contributions.
Button : Suivre 
Label second modal : 
`Vous êtes bien abonné(e) à Selon Que Choisir`
Button : Voir l'exemple

**Comment by MaartenLMEM** [comment]
It s working well ([testing video here](https://drive.google.com/file/d/12Qk1LkoOJa_a04yibwKAbXXnKGxTgbTZ/view)). Just a detail to review with @coffeeandpixel about the modal at the end : 
en tant qu'utilisateur, quand je reviens à ma liste de contributeurs, est-ce que ça ne serait pas mieux que la modale soit fermée ? Sinon je dois recliquer sur la croix pour passer à un autre exemple.

**Comment by MaartenLMEM** [comment]
Marco confirme : il serait préférable que la modale soit fermée après que l'utilisateur ait cliqué sur le lien voir l'exemple. 
En partant du principe que c'est un petit ajout XS je te repasse la main @gregoirelacoste
