### ISSUE TITLE
Staging : Onboarding triggers every time I go to "dismoi.io/eclaireurs"

### ISSUE THREAD

**Issue by christpet** [dis-moi/extension#891]
**Describe the bug**
This is in the Firefox Staging version found here https://github.com/dis-moi/extension/releases/tag/v3.69.1 

Every time the user goes to https://staging-profiles.dismoi.io/eclaireurs, the Onboarding tutorial plays. Even without the "?installed" URL piece

**To Reproduce**
1. Download the Staging version https://github.com/dis-moi/extension/releases/tag/v3.69.1 
2. Finish the tutorial and go out
3. Navigate to https://staging-profiles.dismoi.io/eclaireurs 
4. See tutorial play

**Expected behavior**
The tutorial should not play except when the URL (https://staging-profiles.dismoi.io/eclaireurs) contains the following: "?pk_campaign=installed"

**Comment by gregoirelacoste** [comment]
@MaartenLMEM I can't reproduce the bug, I think this issue is already fixed. 
@newick could you confirm ?

**Comment by MaartenLMEM** [comment]
ok I consider it fixed, we ll find it back if it comes up again
