### ISSUE TITLE
New Onboarding: evolutions

### ISSUE THREAD

**Issue by newick** [dis-moi/extension#902]
**Describe the feature/improvement**

Few edits before going to prod : 
* separate experience for Firefox and Chrome Users. On Firefox, only 2 steps, not the pinning part.
* update wording to prevent bad experience in case of onboarding reopening.
Instead of "l'installation a réussi", it could be "L'extension est à jour".

@coffeeandpixel will add some design feedbacks.

**Target user**
New Users or 🤞 if we can not find a solution of the reopening of the onboarding

**Comment by gregoirelacoste** [comment]
ok for the first changes, so now I'm waiting for your feedbacks @coffeeandpixel 
PR here: https://github.com/dis-moi/extension/pull/903
