### ISSUE TITLE
Onboarding is not launched after installation

### ISSUE THREAD

**Issue by MaartenLMEM** [dis-moi/extension#905]
**Describe the bug**
Onboarding process is supposed to launch after I install DisMoi. But it does not trigger anything. 
I made 6 tests on staging and proding Firefox, just one time it opened a page. 

@newick and Marco met same problem on Firefox and Chrome and will share more information here after further enquiry

**To Reproduce**
Install Dismoi

**Expected behavior**
Opens onboarding

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser : Firefox

**Extension**
 - Firefox Version 3.71.0
- Installed from Store
- Installation date  : April 16th 2021

**Additional context**
List of other browser extensions?

**Comment by MaartenLMEM** [comment]
@newick this is quite urgent because I cannot test anything seriously related to onbarding

**Comment by newick** [comment]
@MaartenLMEM I tried many times and can't reproduce it anymore…

**Comment by MaartenLMEM** [comment]
ok thanks !  I ll malke a test soon to confirm on my side

**Comment by MaartenLMEM** [comment]
Its ok ! I tested on firefox proding 3.71.3 and firefox prod and chrome prod, it triggered onboarding page each time.
Unsitall page also opened when I uninstalled (two tries).
