### ISSUE TITLE
Opening default profiles page from extension does nothing

### ISSUE THREAD

**Issue by lutangar** [dis-moi/extension#910]
**Describe the bug**
When attempting to open profile page from extension, nothing happens.

**Extension**
[3.71.0](https://github.com/dis-moi/extension/commit/6ca536f7cac1f9679dfb9afdb9641d184cd043c9)

**Additional context**
This is because we don't wait for the `i18n` `t` function to be ready, hence default `path` is undefined.

**Comment by MaartenLMEM** [comment]
FYI I have tried to reproduce bug on recetn staging and proding versions, It did not happen.
