### ISSUE TITLE
Certain Xpath-embedded notices seem to have wrong stats (data the same with other notices)

### ISSUE THREAD

**Issue by zhinu** [dis-moi/extension#920]
**Describe the bug**
We are having wrong backend data on certain notices that have an xpath connector.
![image](https://user-images.githubusercontent.com/75084558/115518833-e9669c00-a288-11eb-9453-d99ddffdc862.png)

When I visit a page where the notice should show (ie: https://www.leboncoin.fr/consoles_jeux_video/1959949521.htm?ac=2404136686), 3 badges and 1 aperçu are counted.

This is pretty problematic, since we are already facing issues having clean data.

Edit: it seems it occurs with notices that share the regex 
> .*

**Comment by lutangar** [comment]
I did some digging and I'm creating some testing data in `dev` environment but so far I didn't experience the issue. I'm not saying it doesn't exist, but so far I can't reproduce it with my testing data. 

I'll try to create smthing on *lbc* to see if it's related to this specific website... 

What I can tell so far:
- *so far* `xpath` doesn't *seem* to be responsible
- 2 *matching* `matchingContext` for the same notice on same URL don't trigger 2 displays or 2 badges (at least when pressing F5)

I'd like some precision from you guys :
- @zhinu is saying 3 badges and 1 display...
- @Etienne-DisMoi saying ? badges and 2 display...

On the screenshot you're showing 3 notices, on which one are you both testing?
Let's choose `1875` test again and give me a few more informations:

- URL you're testing on
- How do you trigger the notice: Hitting refresh? Or navigating to the URL from another one?

**Desktop**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, Firefox]

**Extension**
- Version [e.g. 3.55.4]

**Comment by lutangar** [comment]
After more investigation...

LBC is a "special case":
1. Go to a matching URL: Badge show 2 notices and the UI opens.
2. Navigate to another URL on LBC:  The Badge still show 2 notices ....

If you inspect the source of the page and press `Ctrl+F` there, you'll notice 2 things:
1. Informations of your previous page is present in `script`:
```
<script id="__NEXT_DATA__" type="application/json" crossorigin="anonymous">
///...
</script>
```
> Probably coded in `next.js`

2. There is an `xpath` search which might be very handy for you :D

![Screenshot from 2021-04-27 15-45-21](https://user-images.githubusercontent.com/568769/116252233-ab2d1900-a76f-11eb-94dc-48ef9cd424e8.png)

What we can guess from this, is, every next page visited page on LBC will count as badge + display. So maybe each notices triggers on LBC may reach similar stats given sufficient time?

**Comment by lutangar** [comment]
For this usecase, my suggestion is then to use a more precise `xpath`:
```
//div[@id='__next']//text()[contains(.,'search')]
```

Overall you should try to use selector targeting an area of the page instead of the whole page to avoid false positive.

**Comment by zhinu** [comment]
Bravo!!! I'm pretty sure you solved the mystery!!!
Changing the xpaths now :)

**Comment by zhinu** [comment]
All the notices that had this issue were targeting leboncoin.fr
