### ISSUE TITLE
go back to "Abonnements" instead of "vos éclaireurs"

### ISSUE THREAD

**Issue by gregoirelacoste** [dis-moi/extension#929]
@gregoirelacoste sorry for chaging this, but we go back to "Abonnements" instead of "vos éclaireurs" 
Is it possible to simply roll back ?

_Originally posted by @MaartenLMEM in https://github.com/dis-moi/extension/issues/804#issuecomment-827854122_

**Comment by gregoirelacoste** [comment]
files here: https://github.com/dis-moi/extension/tree/master/src/i18n/resources

**Comment by gregoirelacoste** [comment]
@MaartenLMEM i am a bit lost on this issue, have you already handle it?

**Comment by MaartenLMEM** [comment]
I still have a part to finish, I handle it thanks
