### ISSUE TITLE
Modal: "Suivre et Voir l'exemple" in two steps

### ISSUE THREAD

**Issue by gregoirelacoste** [dis-moi/extension#933]
Label first modal :  
Veuillez suivre Colibri écolo pour voir ses contributions.
Button : Suivre 
Label second modal : 
`Vous êtes bien abonné(e) à Selon Que Choisir`
Button : Voir l'exemple

_Originally posted by @MaartenLMEM in https://github.com/dis-moi/extension/issues/890#issuecomment-828280730_

**Comment by gregoirelacoste** [comment]
@MaartenLMEM  To see the example of a contributor, for a user who already owns the extension but not following yet the contributor,

1. on see example button click, a popin is displayed inviting him to follow the contributor
![image](https://user-images.githubusercontent.com/60737012/116430020-bc952480-a846-11eb-97bc-bcfbbfb5cae3.png)
2. when clicking on "follow", a second confirmation popin appears then invites the user to see the example
![image](https://user-images.githubusercontent.com/60737012/116430751-696fa180-a847-11eb-833c-29667f243642.png)

**Comment by MaartenLMEM** [comment]
thanks ! ok I made a little mistake on first label. It should be "Suivre".

**Comment by gregoirelacoste** [comment]
@MaartenLMEM ok for the french, for english i suggest: 
```json
"message": "Please follow {{contributorName}} to see his contributions",
"btn_text": "Follow"
```

```json
"message": "You just subscribed to {{contributorName}}",
"btn_text": "See example"
```
ok ?

**Comment by MaartenLMEM** [comment]
Just add the case of woman contributor : "Please follow {{contributorName}} to see his**/her** contributions",

After, for these texts, I d feel more confortable if @prk-dismoi could say if correct english idomias are used here. Can have a look @prk-dismoi ?

**Comment by prk-dismoi** [comment]
just one change, his > their (covers both genders)

"message": "Please follow {{contributorName}} to see their contributions",
"btn_text": "Follow"
"message": "You just subscribed to {{contributorName}}",
"btn_text": "See example"

**Comment by gregoirelacoste** [comment]
@prk-dismoi you would like to change the translation ? ok I reopen this ticket and add in TODO list

**Comment by prk-dismoi** [comment]
Just replying to question from Maarten from Friday. I guess you will have to reopen, sorry for the extra work.

**Comment by MaartenLMEM** [comment]
I take it, thanks guys !

**Comment by MaartenLMEM** [comment]
@gregoirelacoste  J'ai testé tout fonctionne bien.
Une chose supplémentaire pour cette feature : Quand je reviens à ma liste de contributeurs, la modale soit être fermée, afin que je continue à découvrir les contributeurs. On en discute tout à l'heure.

**Comment by MaartenLMEM** [comment]
When testing staging I discovered a bug not caused by this feature but related to another recent dev https://github.com/dis-moi/extension/issues/953
