### ISSUE TITLE
On contribution: In staging firefox, error message appear 

### ISSUE THREAD

**Issue by gregoirelacoste** [dis-moi/extension#940]
Contribution is working very well, with delicious details in the process. 

But as a question is not working. In staging firefox, I had this error message : 
![image](https://user-images.githubusercontent.com/7824485/116584675-e36f5b80-a917-11eb-95cf-74751de5ba46.png)

I made different tests on lequipe also, same result.
Here is a part of background that seem linked to this new issue :

![image](https://user-images.githubusercontent.com/7824485/116585402-a788c600-a918-11eb-9b32-55a968f1d6cd.png)

![image](https://user-images.githubusercontent.com/7824485/116585671-eae33480-a918-11eb-815d-c80f023b334c.png)

_Originally posted by @MaartenLMEM in https://github.com/dis-moi/extension/issues/800#issuecomment-829382120_

**Comment by MaartenLMEM** [comment]
I think @lutangar worked on this so I set you as assignee.
