### ISSUE TITLE
From proding, we're sending event to production db on the backend whereas we shouldn't

### ISSUE THREAD

**Issue by MaartenLMEM** [dis-moi/extension#961]
**Problem :** 
Contribution is doing many test and improvment on notices. Also product team need to test bugs etc. 
All these behaviours are counted in backoffice statistics.
It impacts data reliability for bubble with less than 100 actions and can mislead or make impossible to make decisions based on little samples. 

**Solutions**
1. Analytics opt-ou preference in extension : https://github.com/dis-moi/extension/issues/745
2. Make a special extension "Prod testing extension" that each member of DisMoi will use.
This add-on doesn"t trasnmit behaviours data to Matomo, nor to the backoffice. 
It would be deployed in the same time as chrome proding and staging.

Solution 1 is probably the best one.

**Comment by lutangar** [comment]
Currently backend tracked events include the followings:
```
export type FeedbackType =
  | 'dismiss'
  | 'confirmDismiss'
  | 'undismiss'
  | 'like'
  | 'unlike'
  | 'dislike'
  | 'confirmDislike'
  | 'undislike';
```
Just wanted to mention we'll also ignore `like` related events.

**Comment by MaartenLMEM** [comment]
Just to be sure @lutangar : I do not see badges, bubble views, etc. those are most important events to ignore

**Comment by lutangar** [comment]
Yes they will be ignored.

Technical wording for these are the following:
- NOTICE_UNFOLDED
- NOTICE_BADGED
- OUTBOUND_LINK_CLICKED
- RatingType.OUTBOUND_CLICK
- NOTICE_DISPLAYED

There was even a schema for these if I recall correctly.

**Comment by MaartenLMEM** [comment]
it s ok I verified it, don't bother @zhinu
