### ISSUE TITLE
Add link "voir ses contributions" on page "followed profiles"

### ISSUE THREAD

**Issue by MaartenLMEM** [dis-moi/extension#966]
Link "voir ses contributions" has disappeared on "contributeurs suivis" onglet 

![image](https://user-images.githubusercontent.com/7824485/117856905-7a2f0700-b28c-11eb-9596-4ca97fd4e904.png)

**Comment by gregoirelacoste** [comment]
It seems to be a new feature and not a bug. Indeed, I don't see this link in Prod or in the code

**Comment by MaartenLMEM** [comment]
ok thanks I put in backlog for later

**Comment by MaartenLMEM** [comment]
You added link voir un exemple instead of "voir ses contributions"
But it s ok, probably a better choice.  Thanks.
