### ISSUE TITLE
New title SERP profile page : Name + contributeur sur DisMoi

### ISSUE THREAD

**Issue by MaartenLMEM** [dis-moi/extension#977]
very close to https://github.com/dis-moi/extension/issues/978 

**Describe the feature/improvement**
Modifier la balise Title référencée pour les contributeurs par les robots Google 
Par exemple, sur Le Meme en Local,  
à la place : "Le Même en Local - Source d'information sur DisMoi".
mettre "Le Même en Local - Contributeur sur DisMoi"

**Comment by gregoirelacoste** [comment]
@MaartenLMEM c'était sur le site wordpress, c'est mis en prod avec @antoinewolff
