### ISSUE TITLE
Cannot follow a new contributor

### ISSUE THREAD

**Issue by felix-lambert** [dis-moi/extension#982]
When I want to follow wirecutter I have a message saying that I need to install the extension. But the extension is already installed on my browser

**Comment by MaartenLMEM** [comment]
@felix-lambert it s happening on mobile I suppose ?

**Comment by felix-lambert** [comment]
Non je l'ai sur desktop firefox

**Comment by MaartenLMEM** [comment]
Ok merci. Alors je ne peux pas reproduire de mon côté. 
Peux tu compléter les éléments suivants stp  :

**Extension**
- Proding / Staging / Prod ?
- Version [e.g. 3.55.4]
- Installed from [Store/Github release/Source]

**Desktop (please complete the following information):**
 - OS: 
 - Firefox Version ...

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
