### ISSUE TITLE
strange anchor when I share a profil link on trello

### ISSUE THREAD

**Issue by MaartenLMEM** [dis-moi/extension#990]
Instead of the title 'Le même en local', it s the description that is shared as anchor :

![image](https://user-images.githubusercontent.com/7824485/118867425-5c445080-b8e3-11eb-8495-e75fe1fe1384.png)

**Comment by antoinewolff** [comment]
@MaartenLMEM : I don't success to reproduce the problem. But if you check the result of the data fetched by Facebook (for example) it seems that it's ok : https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fwww.dismoi.io%2Feclaireurs%2F120%2FLavar-din-Dis-moi
