### ISSUE TITLE
Cannot see all the notices when there is more than 2 notices

### ISSUE THREAD

**Issue by felix-lambert** [dis-moi/extension#997]
Extension

    Prod
    Version 3.61.0
    Installed from Firefox

Follow the 6 first contributors and wirecutter
    Go to 'https://www.amazon.com/Apple-AirPods-Charging-Latest-Model/dp/B07PXGQC1Q'
    You can see a notification saying that your have 3 contributions on this page but you will only see 2 contributions and you cannot scroll down

**Comment by MaartenLMEM** [comment]
solved and in production since today
